### ISSUE TITLE
Bit of help with c# Windows Form App using AMI

### ISSUE THREAD

**Issue by DaveTTS** [AsterNET/AsterNET#100]
Hi all

I have a console app working with the AMI using Asternet fine, but I want to migrate over to using a c# windows form app, so I can show within the app what events are happening and statuses etc etc.

I have an issue with threading.  When I move from the console over to the form app, when I try to update the UI with the event I get an error Cross-thread operation not valid - makes sense as the event does not know about the thread of the application so it errors, however I'm having much trouble trying to work out how to make it work.  I guess using a delegate is the way forward.

Currently, I use:

 manager.NewExten += new NewExtenEventHandler(event_NewExten);

with my event Handler of

 void event_NewExten(object sender, NewExtenEvent e)
        {
            txt_Output.Text = txt_Output.Text + "\r\n" + "event_NewExten Fired";
            txt_Output.Text = txt_Output.Text + "\r\n" + "New Extension Event\r\n"
                + "Channel: " + e.Channel + "\r\n"
                + "Extension: " + e.Extension + "\r\n"
                + "Context: " + e.Context + "\r\n"
                + "DateReceived: " + e.DateReceived + "\r\n"
                + "Priority: " + e.Priority + "\r\n"
                + "Privilege: " + e.Privilege + "\r\n"
                + "UniqueId: " + e.UniqueId + "\r\n"
                + "AppData: " + e.AppData + "\r\n"
                + "Application: " + e.Application;

            txt_Output.Text = txt_Output.Text + "\r\n" + "Attributes:\r\n";
            foreach (System.Collections.Generic.KeyValuePair<string, string> pair in e.Attributes)
            {
                txt_Output.Text = txt_Output.Text + "\r\n" + String.Format("\t{0}\t{1}", pair.Key, pair.Value);
            }

        }

What I have just got working is:

  void event_NewExten(object sender, NewExtenEvent e)
        {

            // Running on the worker thread
            string newText = txt_Output.Text + "\r\n" + "event_NewExten Fired";
            txt_Output.Invoke((MethodInvoker)delegate { txt_Output.Text = txt_Output.Text + "\r\n" + newText; });
}

But I do not know if this is the best or recommended way of doing it.

Thanks

David

**Comment by Deantwo** [comment]
See: https://msdn.microsoft.com/en-us/library/ms171728(v=vs.110).aspx

**Comment by DaveTTS** [comment]
Thanks Deantwo that's most helpful
