### ISSUE TITLE
DNIS for inbound calls

### ISSUE THREAD

**Issue by chrishem** [AsterNET/AsterNET#101]
Would it be possible to have an inbound call event provide the [DNIS](https://en.wikipedia.org/wiki/Dialed_Number_Identification_Service) of the call? 
I'm currently catching the NewStateEvent, and looking to see if the ChannelState is "Ringing" (5), as well as a couple of other "filters". It would be nice to have the number which was dialed be part of the Event.

**Comment by skrusty** [comment]
This isn't within the scope of AsterNET. Information passed in events is controlled by Asterisk. If Asterisk can provide the information over AMI, then AsterNET can receive it.

See: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+AMI+Events

**Comment by chrishem** [comment]
I was able to massage my code around the VarSet event to give me the data I wanted. Thanks for the pointer to the AMI events, it helped a lot!
