### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by manika880** [AsterNET/AsterNET#106]
I am facing the Authentication failed problem during login action is executed.
        const string DEV_HOST = "192.168.13.36";
        const int ASTERISK_PORT = 5038;
        const string ASTERISK_HOST = "192.168.13.36";
        const string ASTERISK_LOGINNAME = "admin";
        const string ASTERISK_LOGINPWD = "secret";

I can login on my asterisk server by using above credential. After successful login, it lands up on dashboard. But i am not able to make a successful login through code. Where am i going wrong.
Any help would be much appreciated.

**Comment by skrusty** [comment]
I assume you're using some Asterisk based PBX, not vanilla Asterisk. Don't assume your login details are also valid AMI login details.

**Comment by manika880** [comment]
Yes you are right. I am using Asterisk based PBX. So how can i get the login details of AMI? I looked into the pbx setting and found that there is manager.config for AMI details and I tried to login by using that AMI login details but getting same error. My AMI details looks something like that:

[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0
displayconnects=no ;only effects 1.6+


[admin]
secret = amp111
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

**Comment by skrusty** [comment]
Looks like you're not permitting anything but localhost?

**Comment by manika880** [comment]
How can I permit for other IPs?

**Comment by manika880** [comment]
This issue has gone after writing
[admin]
secret = amp111
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.0
permit=(ANY IP)/255.255.255.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000
and then  reload asterisk server.
