### ISSUE TITLE
How to create extension from my .net application

### ISSUE THREAD

**Issue by manika880** [AsterNET/AsterNET#108]
I am developing an .NET MVC application. Now i need to create extension from my application rather than to create from asterisk dashboard. How can i do that? Please provide the code for the same.

Any help would be much appreciated.

**Comment by 91Abdullah** [comment]
I guess you'll be needing some .NET remote FTP library.

**Comment by skrusty** [comment]
Maybe look at using Asterisk Realtime configuration (db backed peers etc) and not the config files.

This is more an Asterisk question, then AsterNET.
