### ISSUE TITLE
Conflict AsterNET .dll version GitHub vs NuGet

### ISSUE THREAD

**Issue by omidnasri** [AsterNET/AsterNET#111]
Today i see the [Telnet Issues](https://github.com/AsterNET/AsterNET/issues/75) that fixed by [Spmoolman](https://github.com/Spmoolman) and updated [AsterNET repository](https://github.com/AsterNET/AsterNET/commit/714482d9030233c5dfd2f1a68478c5cdca01a605) master but NuGet version conflict with current GitHub version, please update AsterNET NuGet file.
![capture](https://user-images.githubusercontent.com/11842391/27585940-12bf3a58-5af3-11e7-946b-5248e79d4748.PNG)

Click [here](https://www.nuget.org/packages/AsterNET/) for redirect to AsterNET NuGet page.

**Comment by skrusty** [comment]
I will work towards a refresh of nuget this week.

**Comment by MattDBP** [comment]
The 1.2 nuget release also appears to be missing the following events for bridges

BridgeCreate
BridgeDestroy
BridgeEnter
BridgeLeave

**Comment by Pazkov** [comment]
Can you please update the nuget package with the correct 1.2.0 version?
The nuget 1.2.0 package seems to be the 1.0.1 GitHub 

Thanks

**Comment by skrusty** [comment]
will be looking at this tonight along with another nuget issue.

**Comment by Pazkov** [comment]
Any news?
The nuget package seems the same.
Thanks

**Comment by Deantwo** [comment]
I guess this was never fixed and is related to #126.

**Comment by Deantwo** [comment]
This should be fixed now.
