### ISSUE TITLE
Is ManagerConnection thead safe?

### ISSUE THREAD

**Issue by squaregear** [AsterNET/AsterNET#114]
In a multithreaded app, is it safe to have multiple threads using the same instance of ManagerConnection? Or do calls like SendAction() and SendEventGeneratingAction() need to grab a lock first?

**Comment by tutifrutas** [comment]
It is not thread safe, unless I missed something writing to the tcp client is not thread safe.

**Comment by skrusty** [comment]
No, it's not. Suggestions for version two welcome though.
