### ISSUE TITLE
Unable to receive events from Freepbx

### ISSUE THREAD

**Issue by kashifiqb** [AsterNET/AsterNET#118]
I installed Freepbx version from here: https://www.freepbx.org/downloads/ (the Legacy one) and configured  Manager User in it. Now I can login to the server using AsterNET and commands work like adding a number to blacklist.

My aim is to monitor the incoming call alert events when a call is made. For this I subscribed to the events as well. However, no incoming call alert is generated in my .NET application when call is made. Can anyone help in this? Which versions of Asterisk are supported by this API at this time?

**Comment by skrusty** [comment]
You need to ensure you've subscribed your account in manager.conf to the event types you want to receive.

```
[mark]
  secret = mysecret
  deny=0.0.0.0/0.0.0.0
  permit=209.16.236.73/255.255.255.0
  permit=127.0.0.1/255.255.255.0
  read = system,call,log,verbose,command,agent,user,originate
  write = system,call,log,verbose,command,agent,user,originate
```

**Comment by kashifiqb** [comment]
@skrusty ,

Can you please point me to where I can find the manager.conf?

**Comment by kashifiqb** [comment]
I checked the Permissions and all are marked as allowed: http://prntscr.com/h4a8k8

**Comment by kashifiqb** [comment]
@skrusty ,

I now executed Asternet.Test sub-project and it started printing all events to output from this method:

```
static void dam_Events(object sender, ManagerEvent e)
{
	Console.WriteLine(e);
}
```
Its lots of data. Other events like dam_Dial, dam_Hangup are never ever triggerred. I have also set eventwhencalled to Yes in Freepbx configuration, but still no event is generated. 

Can any one help in this?

**Comment by hugodeco** [comment]
Its true, after asterisk 13 these events are not reconized and not used anymore.
Whats the porpose of your application ?

Enviado do Email para Windows 10

De: kashifiqb
Enviado:terça-feira, 31 de outubro de 2017 12:15
Para: AsterNET/AsterNET
Cc:Subscribed
Assunto: Re: [AsterNET/AsterNET] Unable to receive events from Freepbx (#118)

@skrusty ,
I now executed Asternet.Test sub-project and it started printing all events to output from this method:
static void dam_Events(object sender, ManagerEvent e)
{
	Console.WriteLine(e);
}
Its lots of data. Other events like dam_Dial, dam_Hangup are never ever triggerred. I have also set eventwhencalled to Yes in Freepbx configuration, but still no event is generated.
Can any one help in this?

**Comment by kashifiqb** [comment]
Here is the scenario:

* Agent is logged to a IP Phone  with extension 100
* He also has my application running in front of him where callers information is displayed
* I want that when a call is made from 101 to 100, my application should display the caller number to the  agent in my application. This caller number will also help me link the caller information to my database of callers for info such as name, address, etc.

So, the aim is to get caller alert with caller id in my application which I was hoping to get through this event. Also, if call disconnection/completion event is fired, it will help log the total time duration of the call in my application for record.

Any idea please?

**Comment by hugodeco** [comment]
Ok, the best way to do that is with the Status Events.

The Dial is Async and can be lost on network problems.

Using the StatusCommand you will have a better info about the active channels. U Can run these an 2 seconds interval and check the diferences between than.

Enviado do Email para Windows 10

De: kashifiqb
Enviado:terça-feira, 31 de outubro de 2017 12:22
Para: AsterNET/AsterNET
Cc:hugodeco; Comment
Assunto: Re: [AsterNET/AsterNET] Unable to receive events from Freepbx (#118)

Here is the scenario:
• Agent is logged to a IP Phone with extension 100
• He also has my application running in front of him where callers information is displayed
• I want that when a call is made from 101 to 100, my application should display the caller number to the agent in my application. This caller number will also help me link the caller information to my database of callers for info such as name, address, etc.
So, the aim is to get caller alert with caller id in my application which I was hoping to get through this event. Also, if call disconnection/completion event is fired, it will help log the total time duration of the call in my application for record.
Any idea please?

**Comment by kashifiqb** [comment]
Can you please give me an example code? Much appreciated if you could share a sample.

**Comment by hugodeco** [comment]
My CODE !!! Private ?!!!! and sorry its in Portuguese.

// EVERY 2 SECONDS
static void manutencaoRelatorio(Object stateInfo)
        {
            if (Gatilho["Manutencao"])
            {
                if (!Gatilho["Manutencao-Trabalhando"] || (StatusLastAction.AddSeconds(10) < DateTime.Now))
                {
                    Gatilho["Manutencao-Trabalhando"] = true;
                    try
                    {
                        if (PAsterisk.AManager.IsConnected())
                        {
                            ManagerResponse resposta;
                            resposta = PAsterisk.AManager.SendAction(new StatusAction(), 2000);
                            StatusActionID = resposta.ActionId;
                            StatusLastAction = DateTime.Now;
                            Contador["Manutencao-Relatorio"] = 0;
                        }
                        else
                        {
                            Gatilho["Manutencao-Trabalhando"] = false;
                            Contador["Manutencao-Erro"]++;
                            if(Gatilho["Depuracao"]) Sufficit.Sistema.Alerta(Sufficit.Comunicacao.TMensagem.Depuracao, "erro ao enviar comando de status: não conectado");
                        }
                    }
                    catch (Exception ex)
                    {
                        Gatilho["Manutencao-Trabalhando"] = false;
                        Contador["Manutencao-Erro"]++;
                        if(Gatilho["Depuracao"]) Sufficit.Sistema.Alerta(Sufficit.Comunicacao.TMensagem.Erro, "erro ao enviar comando de status", ex);
                    }
                }
                else { Contador["Manutencao-Sobrecarga"]++; }
            }

            try
            {
                IEnumerable<Canal> inativos = Canais.Values.Where(subitem => !subitem.Ativo && Ferramentas.ToDateTime(subitem.TimeStamp).AddMinutes(2) < DateTime.Now);
                foreach(Canal item in inativos)
                {
                    lock (_canais) _canais.Remove(item.ID);   
                }
            }catch(Exception ex) { Sufficit.Sistema.Alerta(Sufficit.Comunicacao.TMensagem.Erro, "erro ao remover canal do cache", ex); }
        }


// EACH CHANNEL WILL GENERATE ONE OF THAT, SUM THEN ALL
static void eventoTipoStatus(object sender, StatusEvent Evento)
        {
            try
            {
                Contador["Manutencao-Relatorio"]++;
                if (Depuracao.Gatilho["Status"]) Depuracao.Depurar(Evento);
                if (!String.IsNullOrWhiteSpace(Evento.ActionId) && StatusActionID == Evento.ActionId)
                    eventoPreparar(Evento);
                //else Contador["Manutencao-Divergente"]++;
            }
            catch (Exception ex) { Sufficit.Sistema.Alerta(Sufficit.Comunicacao.TMensagem.Erro, "erro ao processar EVENTO Tipo Status asdasdasd", ex); }
        }

// GET INFO AFTER COMPLETE AND CHECK WITH PAST SUM, CONSISTENCE
        static void eventoTipoStatusComplete(object sender, StatusCompleteEvent Evento)
        {
            try
            {
                if (Depuracao.Gatilho["StatusComplete"]) Depuracao.Depurar(Evento);
                if (Evento.Items == Contador["Manutencao-Relatorio"])
                {

                    foreach (Canal item in Ativos.Where(sub => sub.Value.TimeStamp <= Evento.Timestamp).Select(subitem => subitem.Value))
                    {
                        if (!String.IsNullOrWhiteSpace(Evento.ActionId) && item.UltimoEventoStatus != Evento.ActionId) canalHangup(item.Eventos.Last());
                    }

                }
                else
                {
                    Contador["Manutencao-Divergente"]++;
                    foreach (Canal item in Ativos.Where(sub => (sub.Value.TimeStamp + (Intervalo * 5)) < Evento.Timestamp).Select(subitem => subitem.Value))
                    {
                        canalHangup(item.Eventos.Last(), "sem evento de status por ( ms ): " + Intervalo * 5);
                    }
                }
            }
            catch (Exception ex) { Sufficit.Sistema.Alerta(Sufficit.Comunicacao.TMensagem.Erro, "erro ao processar EVENTO Tipo Status gfd gfg", ex); }
            Gatilho["Manutencao-Trabalhando"] = false;
        }

// AGREGATE TO FORM CHANNELS AND PREPARE TO RECOGNIZE THE CALLS
static bool eventoPreparar(AsterNET.Manager.Event.ManagerEvent Evento)
        {
            Contador["Eventos-Total"]++;            
            if (!Gatilho["Eventos-Ignorar"])
            {
                if (Evento != null && !String.IsNullOrWhiteSpace(Evento.Channel))
                {
                    Contador["Eventos-Validos"]++;
                    if (!String.IsNullOrWhiteSpace(Evento.Channel))
                    {
                        Contador["Eventos-Processados"]++;
                        return canalVincular(Evento);
                    }else Contador["Eventos-Descartados"]++;
                }
                else Contador["Eventos-Nulos"]++;
            } else Contador["Eventos-Ignorados"]++;
            return false;
        }

**Comment by kashifiqb** [comment]
Sorry but that is totally non-understandable due to language :(

**Comment by hugodeco** [comment]
Kkkkkkk, sorry, can’t help much more !

Enviado do Email para Windows 10

De: kashifiqb
Enviado:terça-feira, 31 de outubro de 2017 12:39
Para: AsterNET/AsterNET
Cc:hugodeco; Comment
Assunto: Re: [AsterNET/AsterNET] Unable to receive events from Freepbx (#118)

Sorry but that is totally non-understandable due to language :(

**Comment by kashifiqb** [comment]
Never mind.

Can any one else help please?

**Comment by Deantwo** [comment]
@kashifiqb, what the event are you trying to receive? Which events are you subscribing to?

**Comment by kashifiqb** [comment]
@Deantwo ,

If you configure simple Freepbx with PJSIP extensions and make them part of queue and use this API, you will see that AgentConnect, AgentHangup and ManagerHangup events are raised a lot late.

**Comment by Deantwo** [comment]
I never did quite understand what your question was here.
But if all you want to do is detect when a call is made, I posted some code here: https://github.com/AsterNET/AsterNET/issues/132#issuecomment-361912372

But I have never had the need to see call hangup, so I don't have a good idea about that.

Closing this issue, but if you need more help just reopen it.
