### ISSUE TITLE
Recieve incoming call(answer)

### ISSUE THREAD

**Issue by kapitaneo** [AsterNET/AsterNET#119]
Hello everyone. Now I'm only stating use asterisk, and my question may be stupid. I'm login to asterisk server and i want recive call. When i call from my mobile phone i catch event NewState,  but what need to do next? How can speak using my microphone?)))
I stopped and do not know what to do.
I read some documentation and has concluded than i need use Asternet.ARI, I'm right? 
Please tell me what my next steps, what to use?
Thanks for any help.

**Comment by skrusty** [comment]
And here ends your adventures with AsterNET. Sorry to say, AsterNET only talks AMI (FastAGI). You can't actually interact with the audio of the call (i.e. answer and talk etc) using AMI. 

You can affect the flow of a call, play audio etc, however you're just telling Asterisk to do this, not actually playing the audio yourself.

If you need to create some sort of SIP Client, then i suggest you look at other OS libs that might help (There are quite a few out there).

Sorry we couldn't be more help.
