### ISSUE TITLE
AGIChannel and LastReply

### ISSUE THREAD

**Issue by orastarter** [AsterNET/AsterNET#120]
Hi!
I have faced with bad situation. AGIChannel.LastReply could contain AGIReplay for another AGICommand. I think it is much better to remove field agiReply from AGIChannel and use return value from method SendCommand.
Thank you!

**Comment by skrusty** [comment]
In what context are you using LastReply? I've not seen any issues myself during normal operation. Are you trying to manually query some result?

**Comment by orastarter** [comment]
I haven't use LastReply. I have faced with situation when i send "Exec Dial" and expect result of this command but i have got result of the command "get variable" which I have sent next. I have removed field and rewrite logic to use return value of SendCommand and problem was left.

**Comment by Juan007** [comment]
We've actually come across this issue. We fire just over 6 million events a month, of which about a thousand had this issue. It's when we push high volumes that this happens.

Essentially this is how we retrieved parameters:
```
public static string GetVariable(AGIChannel channel, string name)
        {
            channel.SendCommand(new AsterNET.FastAGI.Command.GetVariableCommand(name));
            if (channel.LastReply.ResultCode != 1)
                return null;
            return channel.LastReply.Extra;
        }
````

We've actually ended up replacing this with a REST call to Asterisk (when fetching multiple parameters we simply fetch them all in parallel).

I would however love to know how the above issue occurs?

**Comment by orastarter** [comment]
I have changed 2 files - AGIChannel and AGIScript. Please check this fix in your side.
[FastAGI.zip](https://github.com/AsterNET/AsterNET/files/2404869/FastAGI.zip)

**Comment by skrusty** [comment]
@orastarter please submit changes as a PR and not a ZIP file. We can't accept any code submitted in any other way then a PR using git.

**Comment by orastarter** [comment]
@skrusty, how can i make PR? I have tried to create branch but i can't publish it:
Error encountered while publishing branch to the remote repository: Response status code does not indicate success: 403 (Forbidden).

**Comment by Deantwo** [comment]
@orastarter, you need to first make your own fork, then make your changes on that fork. Once the fork has your changes you then make a pull request from it to this main repository

**Comment by orastarter** [comment]
@Deantwo Thank you! Next step find VS2017 :)

**Comment by orastarter** [comment]
@Deantwo and @skrusty - done!
