### ISSUE TITLE
What event i can use after redirect call instead AgentConnect?

### ISSUE THREAD

**Issue by razinalexrazinalex** [AsterNET/AsterNET#122]
After call is redirected (by RedirectAction) and operator take it,  event AgentConnect is not rised. What the same event can i use?

**Comment by skrusty** [comment]
The Agent events only get raised from a queue event, as the RedirectAction happens after the queue has handed out the call, this is no longer a queue action (from what I know.

You may be best asking this question in #asterisk on irc.freenode.net
