### ISSUE TITLE
Not subscribing to all events

### ISSUE THREAD

**Issue by brook2006** [AsterNET/AsterNET#124]
Our Asterisk guy says that when I connect to he AMI interface I am not subscribing to events. I have FireAllEvents set to true before I Login, but he still says my session doesn't have events enabled and he has pointed me to [This Page](https://www.voip-info.org/wiki/view/Asterisk+manager+API) which shows an events option with the login action. I have checked the [Asterisk Documentation](https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerAction_Login) and that is missing this parameter. Looking at the [AsterNET Code](https://github.com/AsterNET/AsterNET/blob/b3cd10704383bef1286a24cf9a21039bda3f3c52/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L643) there isn't another option for turn on events either.

So my question is, how do I turn on events if events isn't FireAllEvents?

**Comment by skrusty** [comment]
You should be subscribed to events as part of the manager.conf not as part of you logging into AMI.

You're asterisk tech needs to determine which events you need to be subscribed too. See this: https://www.voip-info.org/wiki/view/Asterisk+config+manager.conf

See the read/write section of the user's config.

**Comment by skrusty** [comment]
Yes, of course it depends on how you're blocking the read thread from ManagerReader.cs.

If you are wait for an event, execute some code inside that event that then waits for another event, you'll be blocking everything else!

You should look at: http://asternet.github.io/AsterNET/html/F_AsterNET_Manager_ManagerConnection_UseASyncEvents.htm
