### ISSUE TITLE
New Asterisk12 Events missing in NuGet version

### ISSUE THREAD

**Issue by Deantwo** [AsterNET/AsterNET#126]
The NuGet version of **AsterNet** seem to be missing the **QueueCallerJoin**, **QueueCallerLeave** and **QueueMemberPause** events.
The events were added in [Asterisk12](https://wiki.asterisk.org/wiki/display/AST/New+in+12).

From what I can see the events do exist in the [GitHub 1.2.0 release](https://github.com/AsterNET/AsterNET/releases/tag/1.2.0).
But they do not seem to appear in the [NuGet 1.2.0 version](https://www.nuget.org/packages/AsterNET/1.2.0).

Anyone able to help confirm this?

**Comment by Deantwo** [comment]
Downloading the [GitHub 1.2.0 release](https://github.com/AsterNET/AsterNET/releases/tag/1.2.0) and referencing to it seems to have the missing events.
So it looks like the NuGet version is indeed not correct.

**Comment by Deantwo** [comment]
If you merge #127, I would love a NuGet update.
But I don't know if anything else should be done first.

**Comment by Deantwo** [comment]
While committing my code changes to my own source control system I noticed this:
``` xml
<Reference Include="AsterNET, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
    <HintPath>..\packages\AsterNET.1.2.0\lib\net40\AsterNET.dll</HintPath>
    <Private>True</Private>
</Reference>
```
It says the version number in the NuGet package is `1.0.0.0`, while the NuGet package itself is named `AsterNET.1.2.0`. So it looks like the NuGet version is actually an older version from before https://github.com/AsterNET/AsterNET/commit/5c5236460788cff46ac19e5f9650c821dc48e05a#diff-0e8d86fe428d40e47056377eb283b404.

**Comment by skrusty** [comment]
Will look at this tonight with a view to fixing it!

**Comment by Deantwo** [comment]
Did you ever release a NuGet update?

**Comment by Deantwo** [comment]
[AsterNET 1.3.0 NuGet](https://www.nuget.org/packages/AsterNET/1.3.0) released.
