### ISSUE TITLE
Auto Anwser

### ISSUE THREAD

**Issue by vladgal** [AsterNET/AsterNET#129]
Hey, I trying to make it auto anwser, and i dont have any clue how to make it

Is there some kind of command I can do it?

my code:
`OriginateAction oc = new OriginateAction();

 oc.Context = "from-internal";

oc.Priority = "1";

oc.Channel = "PJSIP/" + textBox1.Text;

oc.CallerId = textBox2.Text;

oc.Exten = textBox2.Text;

oc.Timeout = 60000;

oc.Async = true;

ManagerResponse originateResponse = manager.SendAction(oc, oc.Timeout);
`

**Comment by skrusty** [comment]
Auto Answer is a feature of a handset, not Asterisk or AsterNET. 

Sometimes it can be done by passing a specific header in the INVITE.

**Comment by vladgal** [comment]
How can i make a specific header?

**Comment by vladgal** [comment]
Because oc.Variable not works foor me

**Comment by skrusty** [comment]
I would start by looking at this, 

https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+Function_PJSIP_HEADER

then join #asterisk on irc.freenode.net or #asterisk-ari on irc.freenode.net

**Comment by vladgal** [comment]
I know the Alert Info
I dont know which command I can to implent it
as OriginateAction.Variable is not working for me
