### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by euripedesaraujo** [AsterNET/AsterNET#136]
I have Issabel 4 with Asterisk 11.

```
var manager = new AsterNET.Manager.ManagerConnection("10.0.1.1", 5038, "admin", "admin");

                manager.Login();
```

Thanks

**Comment by muhammad-naderi** [comment]
what happened here?
is isabbel supported?

**Comment by Deantwo** [comment]
> what happened here?
> is isabbel supported?

What is "Issabel"?
Does it use the Asterisk AMI?

**Comment by muhammad-naderi** [comment]
[Apparently it does , 
](https://www.issabel.com/issabels-new-iso/)so let me ask, if it supports AMI it is good to go? have you ever encountered any limitation on other pbx servers?

**Comment by Deantwo** [comment]
> [Apparently it does , ](https://www.issabel.com/issabels-new-iso/)so let me ask, if it supports AMI it is good to go? have you ever encountered any limitation on other pbx servers?

I personally only use FreePBX, so I don't know.
But if it is just a PBX server that uses Asterisk, then yes it should work if the AMI is setup correctly.

AsterNET doesn't care if Asterisk is run on a toaster or a FreePBX server. As long as the AMI is configured and accessible.
