### ISSUE TITLE
Question to Call

### ISSUE THREAD

**Issue by euripedesaraujo** [AsterNET/AsterNET#137]
Can I do multiple call and receive only when the client answers the call?
I need use the Zoiper? I wanna do without applications.

One example?

**Comment by skrusty** [comment]
No idea what you're asking. AsterNET doesn't actually handle audio, but controls call flow via Asterisk.

**Comment by euripedesaraujo** [comment]
I want to pass a short list of numbers to make calls, and when one is answered be notified and talk.

I can make a call, but I have to set up and use ZoiPer.
