### ISSUE TITLE
Set queue weight

### ISSUE THREAD

**Issue by Javi456** [AsterNET/AsterNET#144]
Hello,

I have been trying to set a queue weight via AsterNet but I only could retrieve the queues parameters. Is it possible to set a certain weight?

Thanks.

**Comment by Deantwo** [comment]
I don't think there is an AMI command that can set the queue weight.
See: https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+AMI+Actions

Queue weight is likely only set in the configuration. But you can give QueueMembers a penalty on specific queues.
See: https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/Action/QueuePenaltyAction.cs
