### ISSUE TITLE
how can I call sendaction continuely 

### ISSUE THREAD

**Issue by liuyang993** [AsterNET/AsterNET#146]
hi 

in AsterNET.WinFrom ,  after AMI success login ,  I add such a botton , which click event code is 

`       

       private void button1_Click(object sender, EventArgs e)
        {

                OriginateAction oc = new OriginateAction();
                oc.Context = @"from-internel";
                oc.Priority = "1";
                oc.Channel = @"Local/6001@from-internel";
                oc.CallerId = ORIGINATE_CALLERID;
                oc.Exten = "6001";
                oc.Timeout = ORIGINATE_TIMEOUT;

                manager.SendAction(oc, null);

                OriginateAction oc1 = new OriginateAction();
                oc1.Context = @"from-internel";
                oc1.Priority = "1";
                oc1.Channel = @"Local/6001@from-internel";
                oc1.CallerId = ORIGINATE_CALLERID;
                oc1.Exten = "6001";
                oc1.Timeout = ORIGINATE_TIMEOUT;

                manager.SendAction(oc1, null);

                OriginateAction oc2 = new OriginateAction();
                oc2.Context = @"from-internel";
                oc2.Priority = "1";
                oc2.Channel = @"Local/6001@from-internel";
                oc2.CallerId = ORIGINATE_CALLERID;
                oc2.Exten = "6001";
                oc2.Timeout = ORIGINATE_TIMEOUT;

                manager.SendAction(oc2, null);

        }`

 I want this part of code can continue make 3 calls on asterisk ,  but in asterisk cli , I find this code only make 1 call  .

here is my dialplan  :  

```
[from-internel]
exten => 6001,1,Dial(Local/7001@from-internel,30)

exten => 7001,1,Answer()
   same => n,Wait(10)
   same => n,Hangup()
```

could anyone tell me how can I make many calls for example in a loop ?

**Comment by liuyang993** [comment]
PS , I find when I set total three event delegate together  in AsterNET.WinFrom 's btnConnect_Click  ,  like this : 

```
            manager.DialBegin += manager_DialBegin;
            manager.DialEnd += manager_DialEnd;
            manager.Hangup += call_hangup_Events;   
```

call_hangup_Events  will not be invoked .

my delegate code is 

```
        void manager_DialEnd(object sender, DialEndEvent e)
        {
           
            DateTime dtAnswerTime = e.DateReceived;
            string sUnique = e.DestUniqueId;

            this.Invoke((MethodInvoker)delegate
            {
                for (int i = 0; i < this.dataGridView1.Rows.Count; i++)
                {
                    if (this.dataGridView1.Rows[i].Cells["uniqueID"].Value.ToString() == sUnique)
                    {
                        this.dataGridView1.Rows[i].Cells["B answer time"].Value = dtAnswerTime;
                    }
                
                }
            });

            return;

        }

        void manager_DialBegin(object sender, DialBeginEvent e)
        {

            string strBnumber = e.DialString;
            DateTime dtRingTime = e.DateReceived;
            string sUnique = e.DestUniqueId;

            this.Invoke((MethodInvoker)delegate
            {
                int index = this.dataGridView1.Rows.Add();
                this.dataGridView1.Rows[index].Cells["B number"].Value = strBnumber;
                this.dataGridView1.Rows[index].Cells["B ring time"].Value = dtRingTime;
                this.dataGridView1.Rows[index].Cells["uniqueID"].Value = sUnique;

                this.dataGridView1.Refresh();
            });

            return;

        }

        void call_hangup_Events(object sender, HangupEvent e)
        {

            string sUnique = e.UniqueId;


            DateTime dtAnswerTime = e.DateReceived;


            this.Invoke((MethodInvoker)delegate
            {
                for (int i = 0; i < this.dataGridView1.Rows.Count; i++)
                {
                    if (this.dataGridView1.Rows[i].Cells["uniqueID"].Value.ToString() == sUnique)
                    {
                        this.dataGridView1.Rows[i].Cells["B hangup time"].Value = dtAnswerTime;
                    }

                }
            });

            return;
        }
```

**Comment by liuyang993** [comment]
From debug , I find it seems because ManagerConnection lose connection problem ,  after success login , during sendaction , the asterisk side cli often show "mark log off"  message , but I do not click the disconnect botton .

**Comment by liuyang993** [comment]
thank you Deantwo ,  after add `oc.Async = true;`  now I can success make 100 calls in a for loop .

**Comment by Deantwo** [comment]
If you don't use `oc.Async = true;`, the Asterisk will wait with replying until both ends of the call either pick up or either side hang up. So your connection likely timed out when AsterNET was setting there waiting.

We can close this issue now?

**Comment by Deantwo** [comment]
I originally learned this from #21, I think.

**Comment by MarcosRoman14** [comment]
I use an asternet and need exec. Action: ExtensionStateList of asterisk actions, but can't find this function
how to use this acction?  thnks

**Comment by Deantwo** [comment]
> I use an asternet and need exec. Action: ExtensionStateList of asterisk actions, but can't find this function
> how to use this acction? thnks

You might wanna make a separate issue. I don't see a connection between this issue and your comment.

**Comment by MarcosRoman14** [comment]
I can't find *ExtensionStateAction *in AsterNET, I try replicate follow the
code-sourse of  *StatusAction *because I need catch in c# system all events
generated with the *Action: ExtensionStateList.*

*regards-*
*thnks.*

**Comment by Deantwo** [comment]
@MarcosRoman14, I understand your issue, but you need to make a new separate issue. You can't just comment on a random old issue.
Here: https://github.com/AsterNET/AsterNET/issues/new
