### ISSUE TITLE
Exceptions in AMI Event Handlers

### ISSUE THREAD

**Issue by jonastelzio** [AsterNET/AsterNET#15]
I want to implement an OnException-event, but I'm struggling with exactly determining where this should be done. Can you give any hints as to where would be a good place?

I need to know if an exception is thrown inside an event handler - currently AsterNET simply consumes them.

**Comment by skrusty** [comment]
It's a good question. The issue is fireEvent uses BeginInvoke, which makes it hard to catch an exception. The answer would be to change the way that fireEvent works. 

Maybe this would be a good opportunity to review this section of code, as I suspect that are much better ways of doing it... Maybe we should look at something a little more modern, such as Task to invoke the handler, and review the task.exception?

Opinions and thoughts welcome.

**Comment by jonastelzio** [comment]
Yeah I'm down for that! I'll get to know the code that dispatches the events, and see if I can think up and then post back here ;)

**Comment by skrusty** [comment]
Cool! Let me know your thought, I'll have a look into it too, see what the current best practises are for handling events async etc.

**Comment by jonastelzio** [comment]
https://github.com/Telzio/AsterNET/commit/ec57910f416e20ce8df2fb5ace0e83cdd69763b5

As a quick measure I've implemented this is my fork (needed something to test on here and now). The code I've written should also work great for the being/end invoke that's in place when UseAsyncEvents are enabled.

I've not tested the being/end implementation there, but it's how I always handled exceptions in asynchronous code - so it should work just fine.

**Comment by skrusty** [comment]
Let me know how you get on, when you think it's ready, make a pull request and we'll take a closer look.

**Comment by jonastelzio** [comment]
I have an addition that I'm not sure should make it into this repo or not - but I found it very practical.

As it is now, the reader thread also dispatches the events, and if they take just a 100ms to complete (if there is like a bunch of slow database work going on), the DateReceived time gets behind the actual even date quite a bit.

I've written an event queue that the read thread just adds the events into, and then another thread dispatches them against the event handlers in the order they come in.

This is obviously when not using async events - which I do - need my events in the order they come in ;)

**Comment by skrusty** [comment]
Yeah, I like the idea of an event queue on a separate dispatcher thread. This would also solve the issue of people pushing out actions while in an event handler, which seems to cause some lock-up issues.

Question is, how should it be implemented within ConnectionManager (if at all) or should this be a separate component? Sync event are good in that they maintain order, and for state modelling that is important, but they do seem to cause some confusion too when people request things like peers from within an existing event handler.

**Comment by skrusty** [comment]
maybe this should be moved out into two issues. Eventing and Error handling.

**Comment by skrusty** [comment]
@jonastelzio you should come have a chat with us in #asternet on freenode (irc).

**Comment by jonasswiatek** [comment]
Yeah, right now I threw it into the Connection Manager, with a new class that handles it. But making it more pluggable is definitely a good idea!

I've had to make some of these adjustments rather quickly to progress our own project - but getting it adopted as a community feature (or whatever it should be called), is always optimal for everyone ;)

In my case I use it very specifically for state modelling to track calls for billing purposes, so the times the event was received is essential to me (shame that Asterisk doesn't include this state information in the data sent on AMI).

I'll join the IRC channel later tonight! I'm in the Central Europe Time Zone (Copenhagen).

**Comment by skrusty** [comment]
one day you'll submit that PR ;)
