### ISSUE TITLE
Events with null Attributes on ManagerEvent

### ISSUE THREAD

**Issue by hugodeco** [AsterNET/AsterNET#153]
Hi, i have a system that generates a lot of events per second and some times the system receives events with null attributes, causing crash.

So, i implanted a Dictionary class of non nullable values and keys, thread safe, to avoid crash on system.
if u you like ? => https://github.com/hugodeco/DDictionary
``` C#
public abstract class ManagerEvent : EventArgs, IParseSupport
{
#region Common Event Properties

    /// <summary>
    /// Store all unknown (without setter) keys from manager event.<br/>
    /// Use in default Parse method <see cref="ManagerEvent.Parse(string, string)"/>
    /// </summary>
    public IDictionary<string, string> Attributes { get; } = new DDictionary<string, string>();
```

**Comment by Deantwo** [comment]
`Attributes` is only defined if the event contain unknown parameters. Always check if `Attributes` is defined before trying to access anything in it.

I have been wondering if `Attributes` shouldn't be rewritten to contain all parameters, even if they are known. Since right now it would be a breaking change to add a parameter that isn't already in an event's class, but if `Attributes` contained all parameters it would not be a breaking changes.

**Comment by hugodeco** [comment]
I understand that, i'm not talking about that. Some atributes Values appering null even in string type, so i'have test every call before use the Key. I Have a huge system using AsterNet almost two years and i had to make some changes, to improve processor time and exceptions control.

If u are interest i can show it to you.

**Comment by skrusty** [comment]
Could you please provide some examples. What event models are producing null events. What the exception is that is causing the crash, along with a stack trace.

Thanks

**Comment by Deantwo** [comment]
@hugodeco?

**Comment by Deantwo** [comment]
Can you at least give some information about which dictionary values were returning `null`?

**Comment by hugodeco** [comment]
When we have a huge flow of events, test for null attributes is not sufficient and crashes the system.
e.Attributes["test"] == null
I had to override the Attributes dictionary, including a lock on record to avoid those erros.

**Comment by Deantwo** [comment]
Does this mean you solved your issue?
