### ISSUE TITLE
How to thread safe get the total call duration from Cdr delegate

### ISSUE THREAD

**Issue by liuyang993** [AsterNET/AsterNET#154]
Hi 

in Winform , I define a class to accumulate many calls 's total duration 
`        class SummaryDuration
        {
            public double dDuration = 0.0;
        }`

then implement Cdr delegate by : 

            manager = new ManagerConnection(address, port, user, password);
      
            manager.Cdr += manager_Cdr;

in function manager_Cdr , I  write : 
`void manager_Cdr(object sender, CdrEvent e)`
`{`
`sd.dDuration = sd.dDuration + double.Parse(e.BillableSeconds.ToString());`
`}`

then I concurrent start 100 calls by call
`OriginateAction oc = new OriginateAction();`
`set oc properties ...` 
 `manager.SendAction(oc, null);`
for 100 times , in my environment , every call will connect 10 seconds and hangup , so the total 100 calls 's duration should be 1000 second , but in fact , I find when all calls terminate , sd.dDuration is about 1200+ ,  I guess it most perhaps is multithread problem , but I do not know how to fix it , could anyone help ? 

PS ; here is full code of relative part 

Define
`	

       public partial class FormMain : Form
	{
                      class SummaryDuration
                     {
                          public double dDuration = 0.0;
                      }

                     ...................   other variable 
         }
`

------------------------------------

Cdr delegate 

`       

       void manager_Cdr(object sender, CdrEvent e)
        {
                        sd.dDuration = sd.dDuration + double.Parse(e.BillableSeconds.ToString());
            return;
        }`
--------------------------------------------

Start 100 calls 

`           

            for (int i = 0; i < 100; i++)
            {
                OriginateAction oc = new OriginateAction();
                oc.Async = true;         //very important

                oc.Context = @"autodialer";
                oc.Priority = "1";

                initBNumber = initBNumber + 1;

                oc.Channel = @"sip/astToCCTB1/" + initBNumber.ToString();

                initANumber = initANumber + 1;

                if (initANumber >= 85222940000)
                {
                    initANumber = 85222930000;
                }
                oc.CallerId = initANumber.ToString();
                oc.Exten = "100";
                oc.Timeout = ORIGINATE_TIMEOUT;

                try
                {
                    manager.SendAction(oc, null);
                }
                catch (Exception ep)
                {
                   //MessageBox.Show(ep.Message);
                }

            }`

**Comment by Deantwo** [comment]
I am not sure I totally understand it all. I mean what is your issue? That the [`BillableSeconds`](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/Event/CdrEvent.cs#L40) is not what you expected?

From what I can see the `BillableSeconds` is actually calculated on the Asterisk, so it likely doesn't have anything to do with AsterNET.
See: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_Cdr

**Comment by Deantwo** [comment]
I'll take that as a yes.
