### ISSUE TITLE
I need help With Check Queue Status Event 

### ISSUE THREAD

**Issue by MSProgrammer** [AsterNET/AsterNET#159]
How Get Queue Status Online , It shown only at first time , when Asterisk AMI Try to Connect With 
" ResponseEvents " The AsterNet Get Queue Info , But I Need To Get All Queue Info Immediately.

If have any way To raise that Please Help Me

Thank you

**Comment by Deantwo** [comment]
If you show some of your code, it might be easier to help you.

**Comment by MSProgrammer** [comment]
Hey @Deantwo  ,
Here is My Code How get Queue Information From Asternet
 :  
 manager = new ManagerConnection(ASTERISK_HOST, ASTERISK_PORT, ASTERISK_LOGINNAME, ASTERISK_LOGINPWD);

            manager.Login();
            ResponseEvents re;
            try
            {
                re = manager.SendEventGeneratingAction(new QueueStatusAction());
            }


            catch (EventTimeoutException e)
            {
                re = e.PartialResult;
            }
            foreach (ManagerEvent e in re.Events)
            {

                //لیست و تعداد صف های تعریف شده در استریسک
                if (e is QueueParamsEvent)
                {
                    QueueParamsEvent qe = (QueueParamsEvent)e;
                    var s = qe.Holdtime;
                    lstQueueList.Add(qe.ToString());
                    SetDuration("QueueParamsEvent" + "\n\tQueue:\t\t" + qe.Queue + "\n\tServiceLevel:\t" + qe.ServiceLevel);
                }

   ///نام اعضا و شرایط اعضا در هرکدام از صف های موجود
                else if (e is QueueMemberStatusEvent)
                {
                    QueueMemberStatusEvent qeS = (QueueMemberStatusEvent)e;
                    List<string> _Queue = new List<string>();
                    _Queue.Add(qeS.ToString());
                }
                else if (e is QueueMemberEvent)
                {
                    QueueMemberEvent qme = (QueueMemberEvent)e;
                    lstQueueMemeber.Add(qme.ToString());
                    SetDuration("QueueMemberEvent" + "\n\tQueue:\t\t" + qme.Queue + "\n\tLocation:\t" + qme.Location);
                }
                else if (e is QueueEntryEvent)
                {
                    QueueEntryEvent qee = (QueueEntryEvent)e;
                    SetDuration("QueueEntryEvent" + "\n\tQueue:\t\t" + qee.Queue + "\n\tChannel:\t" + qee.Channel + "\n\tPosition:\t" + qee.Position);
                }
                else if (e is QueueStatusCompleteEvent)
                {
                    QueueStatusCompleteEvent qee = (QueueStatusCompleteEvent)e;
                    SetDuration("QueueEntryEvent" + "\n\tQueue:\t\t" + qee.Attributes + "\n\tChannel:\t" + qee.Channel + "\n\tPosition:\t" + qee.Server);
                }



            }

**Comment by MSProgrammer** [comment]
But I Want to Display it Immediately with Out Check And Tr To connect  Every Where i My code, to See Queue Status
 @Deantwo

**Comment by Deantwo** [comment]
Mmh, never used `SendEventGeneratingAction` before.
Wouldn't it be easier to just subscribe to the events?
``` C#
manager.QueueParams += QueueParamsEvent;
manager.QueueMember += QueueMemberEvent;
manager.QueueEntry += QueueEntryEvent;
manager.QueueStatusComplete += QueueStatusCompleteEvent;
```

Anyway, I am not sure I understand your problem.
You want the information to magically appear immediately whenever and wherever you need it, but without trying to connect? That makes no sense.

**Comment by MSProgrammer** [comment]
Dear @Deantwo , Thank`s For Your Attend , I`m New in AsterNet And trying to find A way that`s help me to use Event Easier and no need To connect to asterisk every time in my Project (Just Once Connect At the first time) And not Raise the Event up every time.
is there any Way ?

**Comment by MSProgrammer** [comment]
@Deantwo , I Try To Find Out Who join to the Queue , with QueueStatusSummery But I Cant Find A way

**Comment by Deantwo** [comment]
If you want to monitor the queues after the first `QueueStatusAction` you need to subscribe to the queue events.
``` C#
manager.QueueMemberAdded += your_QueueMemberAdded_event_handler;
manager.QueueMemberRemoved += your_QueueMemberRemoved_event_handler;
manager.QueueMemberStatus += your_QueueMemberStatus_event_handler;
manager.QueueCallerAbandon += your_QueueCallerAbandon_event_handler;
manager.Join += your_QueueCallerJoin_event_handler; // < Asterisk12
manager.Leave += your_QueueCallerLeave_event_handler; // < Asterisk12
manager.QueueCallerJoin += your_QueueCallerJoin_event_handler; // >= Asterisk12
manager.QueueCallerLeave += your_QueueCallerLeave_event_handler; // >= Asterisk12
```

**Comment by MSProgrammer** [comment]
@Deantwo Thanks Alot
