### ISSUE TITLE
Call start but not firing anyone events

### ISSUE THREAD

**Issue by bcayan** [AsterNET/AsterNET#162]
Hi,

Firstly, sorry my bad english. :)

I logged Asterisk but I am status is paused.
Asterisk taking inbound call and firing my "JoinEvent" but the conversation does not start.
And I change my status is available and the conversation is start. But Asterisk isn't firing anyone events.

I need when anyone call is start then I opening Customer Card. Because of the scenario I don't open Customer Card. Actually I opening Customer Card in "Join Event". 

Which event do I need to use?

Regards.

**Comment by Deantwo** [comment]
Can you show some code?

**Comment by bcayan** [comment]
`private void dam_Events(object sender, ManagerEvent e)
        {
            if (e is ConnectEvent)
            {
            }
            else if(e is AgentConnectEvent)
            {

            }
            else if (e is JoinEvent)
            {
                JoinEvent eventt = e as JoinEvent;

                if (!object.Equals(Application.OpenForms["frmCustomerCard"], null))
                {
                    Application.OpenForms["frmCustomerCard"].Focus();
                }
                else
                {
                    string phoneNumber = eventt.CallerId;

                    if (eventt.CallerId.StartsWith("0850"))
                    {
                        string[] phoneNumberDatas = eventt.Channel.Split('@');
                        phoneNumber = phoneNumberDatas[0].Replace("Local/", "");
                    }

                    frmCustomerCard cCard = new frmCustomerCard(phoneNumber);
                    cCard.ShowDialog();
                }
            }
            else if (e is HangupEvent)
            {
                if (e.Channel.Contains("Agent/"))
                {
                    using (UsersWorkFlow usersFlow = new UsersWorkFlow())
                    {
                        usersFlow.UpdateUserState((int)StateTypeEnum.Trading, DateTime.Now, "");
                    }
                }
            }
            else if (e is NewStateEvent)
            {
            }
            else if (e is LinkEvent)
            {
            }
            else if (e is CdrEvent)
            {
                CdrEvent cdrEvent = e as CdrEvent;

                using (CustomerActionsWorkFlow customerActionsFlow = new CustomerActionsWorkFlow())
                {
                    if (cdrEvent.DestinationContext == "ext-queues") // Gelen Çağrı
                    {
                        customerActionsFlow.CustomerActionInsert((int)CallTypeEnum.Inbound, SessionUser.user.UserId, DateTime.Parse(cdrEvent.StartTime), DateTime.Parse(cdrEvent.EndTime), int.Parse(cdrEvent.BillableSeconds.ToString()), int.Parse(cdrEvent.Duration.ToString()), cdrEvent.Src, int.Parse(cdrEvent.Destination), cdrEvent.UserField);
                    }
                    else // Giden Çağrılar
                    {
                        if (cdrEvent.Channel.Contains("Agent/")) // Manuel Arama
                        {
                            customerActionsFlow.CustomerActionInsert((int)CallTypeEnum.Outbound, SessionUser.user.UserId, DateTime.Parse(cdrEvent.StartTime), DateTime.Parse(cdrEvent.EndTime), int.Parse(cdrEvent.BillableSeconds.ToString()), int.Parse(cdrEvent.Duration.ToString()), cdrEvent.Destination, 0, cdrEvent.UserField);
                        }
                        else if (!object.Equals(cdrEvent.DestinationChannel, null) && cdrEvent.DestinationChannel.Contains("Agent/") && cdrEvent.Channel.Contains("Local/")) //Dialer Arama
                        {
                            string[] phoneNumberDatas = cdrEvent.Channel.Split('@');
                            string phoneNumber = phoneNumberDatas[0].Replace("Local/", "");

                            string[] queueDatas = cdrEvent.LastData.Split('|');
                            int queueNumber = int.Parse(queueDatas[0]);

                            customerActionsFlow.CustomerActionInsert((int)CallTypeEnum.Dialer, SessionUser.user.UserId, DateTime.Parse(cdrEvent.StartTime), DateTime.Parse(cdrEvent.EndTime), int.Parse(cdrEvent.BillableSeconds.ToString()), int.Parse(cdrEvent.Duration.ToString()), phoneNumber, queueNumber, cdrEvent.UserField);
                        }
                    }
                }
            }
        }`

**Comment by Deantwo** [comment]
The `JoinEvent` (or `QueueCallerJoinEvent` for >=Asterisk12) is raised when a caller enters a phone queue.

When you are paused in the queue, you won't receive calls. So I assume that your dial-plan is sending calls to the queue when you aren't available.

I suggest checking your Asterisk dial-plan. This does not sound like a AsterNET issue, so I can help much.
If what you want is a event when you receive a call, I suggest looking at this: https://github.com/AsterNET/AsterNET/issues/132#issuecomment-361912372

**Comment by bcayan** [comment]
I think I need is this. I will examine. Thank you @Deantwo
