### ISSUE TITLE
BindPort ignored?

### ISSUE THREAD

**Issue by Juan007** [AsterNET/AsterNET#185]
I might be understanding this wrong, but we've got two instances of FastAgi running on the same server. Basically I set the ports, and all should be fine:
``` C#
agi = new AsteriskFastAGI();
//...
agi.BindPort = 1234;// My custom port
agi.Start();
```

However, I still receive this error when starting the second instance (with a different port specified):
```
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at AsterNET.IO.ServerSocket..ctor(Int32 port, IPAddress bindAddress, Encoding encoding) in e:\Projects\Github\AsterNET\Asterisk.2013\Asterisk.NET\IO\ServerSocket.cs:line 19
   at AsterNET.FastAGI.AsteriskFastAGI.Start()
```

What am I missing?!

**Comment by Deantwo** [comment]
Looks like a .Net exception, assigning a port that is already in use?

**Comment by Juan007** [comment]
So to clarify:
Instance 1 was set to start with port `4573` (the default port)
Instance 2 was set to start with port `4574`

If I start instance 1 first, then instance 2 will break with the above error.
If I start instance 2 first, then instance 1 will break with the above error.

Thus it means the two instances compete for the same port (my assumption the default port) ?

I've confirmed, I started the service that has the port setting set to `4574`. Yet if you look at the image, you'll see it started on `4573`

![image](https://user-images.githubusercontent.com/2021922/45832927-89d83680-bd03-11e8-872f-0148d87c001b.png)

**Comment by Deantwo** [comment]
It looks like the port number is used correctly in the code.
See: https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/FastAGI/AsteriskFastAGI.cs#L235

**Comment by Deantwo** [comment]
What is the `ErrorCode` of the expection?
See: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.start?view=netframework-4.7.2

**Comment by Juan007** [comment]
Finally got it working! Thanks for the help!

In the end I changed two things, not sure which helped:
1. Set the port on instantiation: `agi = new AsteriskFastAGI(port, poolSize);`
2. Updated AsterNET nuget package from `1.2.0` to `1.3.0`

**Comment by Deantwo** [comment]
Weird. Don't see why it would have failed in the first place. According to how I read the code and age of the code, neither should have made a difference.
Let me look again.

**Comment by Juan007** [comment]
If you'd like, I could over the weekend write some test code to replicate the issue, then send that along to you? Could easily be a derp on my side! 

Honestly, I'm just happy it works!

**Comment by Deantwo** [comment]
It would be nice if you could try to reproduce it.
If you can't then you can just close this issue.

**Comment by Juan007** [comment]
I've build the code as I called it originally into a test app, and for the life of me cannot replicate. I have no idea what went wrong initially. Thanks for the help!
