### ISSUE TITLE
no call record file with redirect

### ISSUE THREAD

**Issue by stasca84** [AsterNET/AsterNET#191]
Hello!
I work with Asterisk 1.8.15 (I cannot reinstall to the new version for many reasons)
I use AsterNet and C #
When I redirect a call

``` C#
public void RedirectCall (chanel string, peerNum string)
{
    var action = new AsterNET.Manager.Action.RedirectAction (chanel, "from-internal", peerNum, 1);
    var resp = astCon.SendAction (action);
    if (resp! = null)
    {
        var r = (ManagerResponse), respectively;
    }
}
```

There is no call record in the CDR and no wav file.
If you redirect a call from the hardware phone, then there is a record and wav.

I watched the logs, in contrast to the normal call.
In the case of using RedirectCall functions, the MIXMONITOR_FILENAME variable is not set in the VarSet event.
I tried to set it manually, but it did not change anything.
Writing to the CDR is not very important to me. But it is very important for me to create a wav file.
What could be the problem?

**Comment by Deantwo** [comment]
This is not an AsterNET issue, this is simply how Asterisk works. You might have to check if Asterisk has a way to fix it or if updating to a newer Asterisk version would even help.

**Comment by Deantwo** [comment]
Here is the official Asterisk documentation for the v1.8 `Redirect` action.
https://wiki.asterisk.org/wiki/display/AST/ManagerAction_Redirect

**Comment by stasca84** [comment]
Thanks for the answer. There was hope that someone had such a problem.

**Comment by Deantwo** [comment]
I suggest you try the official Asterisk forums instead, might be someone there.

**Comment by stasca84** [comment]
Ok. Thanks. I will try.
