### ISSUE TITLE
Issues with DBPutAction

### ISSUE THREAD

**Issue by moldypenguins** [AsterNET/AsterNET#196]
``` c#
asternet.SendAction(new DBPutAction("/AMPUSER/2001", "cidnum", 2002))
```

this returns success but the values aren't actually being written, not sure where to start on this one

**Comment by Deantwo** [comment]
The Asterisk documentation doesn't say much about that AMI command.
See: https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+ManagerAction_DBPut

**Comment by moldypenguins** [comment]
That I'm not sure of...I'll pull logs in a min once i get this f****g program to run lol

**Comment by moldypenguins** [comment]
`{ManagerResponse {DateReceived:12:36:57 PM; ActionId:99999999_110; Message:Updated database successfully; Response:Success}}
    ActionId: "99999999_110"
    Attributes: null
    DateReceived: {2019-03-27 12:36:57 PM}
    Message: "Updated database successfully"
    Privilege: null
    Response: "Success"
    Server: null
    UniqueId: null
    attributes: null
	
	
	
	
{ManagerResponse {DateReceived:12:37:30 PM; ActionId:99999999_111; Message:Updated database successfully; Response:Success}}
    ActionId: "99999999_111"
    Attributes: null
    DateReceived: {2019-03-27 12:37:30 PM}
    Message: "Updated database successfully"
    Privilege: null
    Response: "Success"
    Server: null
    UniqueId: null
    attributes: null
	
`

**Comment by moldypenguins** [comment]
Inspection of DB (using CLI database show) shows the values didn't change. Has anyone else tried using DBPut before/tested it? Quite possibly is an Asterisk problem but I'm not sure at all.

I did check the docs https://wiki.asterisk.org/wiki/display/AST/ManagerAction_DBPut
Also, I am using version 1.4 but as per docs:
Release 1.4 and later
Set(DB(family/key)=${foo})

**Comment by Deantwo** [comment]
It is pretty hard to google after an answer to this. But maybe it is something simple like not to use a leading `/`?

Try with this:
```C#
DBPutAction("AMPUSER/2001", "cidnum", 2002)
```

**Comment by moldypenguins** [comment]
that was the issue. thank you so much.

on that note maybe a check for leading slash in future versions?

**Comment by Deantwo** [comment]
Sounds dangerous to alter the user's input. In a future Asterisk version it could be a feature to set a leading `/` for example.

Best to just direct people to the (lacking) Asterisk documentation and other resources that describe how to use this AMI command.

I found the answer just by looking at the Asterisk forum, and noticed that no one was using a leading `/`.
