### ISSUE TITLE
Make it easier to extend

### ISSUE THREAD

**Issue by lameventanas** [AsterNET/AsterNET#203]
It would be nice if the classes were easier to extend (eg: ditch the internal modifiers)

**Comment by Deantwo** [comment]
Like, make them `internal protected`?

**Comment by Deantwo** [comment]
Mmh?

**Comment by lameventanas** [comment]
I closed it because I think I shouldn't have opened it in the first place.

Please pay attention to the bugs related to timeouts and disconnections from the manager, in my opinion that is really important.
