### ISSUE TITLE
How to move from parking to queue?

### ISSUE THREAD

**Issue by andrew-paes** [AsterNET/AsterNET#207]
Im using C# AsterNET to manage my Asterisk commands and events, and now I do have a new feature to work on.

This is simple (I think) but I'm stucked right now.

# Scenario
I do have two queues, 8100 and 8300, and 2 extensions being 8101 and 8301. When I do have a call from PSTN it is driven to 8100 queue. When the 8101 extension become available I do add this extension to the 8100 queue, so the calling PSTN device will be redirected to this 8101 extension.

Everything is working fine till here.

Sometimes I do park the calling device and let 8301 knows it using my app, so 8301 user using the same app can send a command asking for that parked channel to be redirect to his SIP Phone. Also working fine.
 
# Scope
Now I want to have some feature to let 8101 transfer this calling device to my other queue, the 8300. So I just tried to reuse my *parked* method and *redirect* method

    internal void Park(string channel, int parkTimeout)
	{
		ParkAction pa = new ParkAction(channel, channel, parkTimeout.ToString());

		ManagerResponse mr = manager.SendAction(pa);
	}

    internal void RedirectFromParking(string channel, string exten)
	{
		RedirectAction ra = new RedirectAction
		{
			Priority = 1,
			Context = "default",
			Channel = channel,
			Exten = exten
		};

		ManagerResponse mr = manager.SendAction(ra);
	}

    Park("abc123456", 10000);

	RedirectFromParking("abc123456", "8300")

# Issue
I'm parking fine but when I try to redirect from parking to my queue the calling device is just disconnected and the connection is lost.

How can I transfer a parked call to my queue or transfer it directly to the queue (would be better) without needing to originate?

**Comment by Deantwo** [comment]
Did you check if the `ManagerResponse` returns with an error state and/or message?

I have never used the "park" feature in Asterisk, so I don't know much about it.
I suggest you check the Asterisk documentation about it, as this doesn't seem like it is a AsterNET issue.

**Comment by andrew-paes** [comment]
> Did you check if the `ManagerResponse` returns with an error state and/or message?
> 
> I have never used the "park" feature in Asterisk, so I don't know much about it.
> I suggest you check the Asterisk documentation about it, as this doesn't seem like it is a AsterNET issue.

ManageResponde just gives me the generic message. I worked around this problem doing the following:

To transfer to a queue I can do a blind transfer as documented on Asterisk website. Links below:

[ManagerAction_BlindTransfer][1]

[ManagerEvent_BlindTransfer][2]

To achieve this using AsterNET, I can use the same *RedirectAction* I was using but I do need to change the context. It can't be *default* for context, as default we are letting Asterisk manage it and somehow it can't handle as I expetected. So it need to be clearly specified as *internar transfer*. The event raised after this context transfer is the *Manager_BlindTransfer*.

[Manager_Action_RedirectAction][3]

So using my SIP Phone I manage to transfer a call while I was debugging that raised event method, so I could catch the context used in. Using the correct context

    ManagerConnection manager = new ManagerConnection(address, port, user, password);

	manager.BlindTransfer += Manager_BlindTransfer;

	private void Manager_BlindTransfer(object sender, BlindTransferEvent e)
	{
		
	}

After this I created another method to transfer to directly to a queue using the correct context.

    internal void TransferToQueue(string channel, string queue)
	{
		RedirectAction ma = new RedirectAction
		{
			Priority = priority,
			Context = "from-internal-xfer",
			Channel = channel,
			Exten = queue
		};

		ManagerResponse mr = manager.SendAction(ma);
	}
	
	TransferToQueue("abc123456", "8300")


#Summary
Was just a matter of the correct context to be used in.

*from-internal-xfer*

  [1]: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_BlindTransfer
  [2]: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_BlindTransfer
  [3]: https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Action_RedirectAction.htm

**Comment by Deantwo** [comment]
Good to hear you got it working.

So we can just close this issue then? Or was there anything in AsterNET that needed changing too?

**Comment by andrew-paes** [comment]
> Good to hear you got it working.
> 
> So we can just close this issue then? Or was there anything in AsterNET that needed changing too?

Yeah, for sure.

Tnx for your time.
