### ISSUE TITLE
Who Hanged Up?

### ISSUE THREAD

**Issue by andrew-paes** [AsterNET/AsterNET#208]
Hi,

I'm a Asterisk 11 user and I'm developing an windows service application using thi library to connect my PBX. Till here everything is working fine, I can send commands and read incoming event messages.

But now I need to develop a feature on my software based over one information that I thought it could be easy to retrieve. The information I'm looking for is - who hanged up?

I googled for it a lot and I could found a few answers, most of them talking about setup the G option on CDR and also some considerations about it. Still like this I couldn't grab any valuable information.

Maybe if I tell you about my working scenario you could help me. Lets go, I'm going to bullet split this:
- I do have a caller calling from a cellphone and this calling are incoming to my internal PBX extension
- My PSTN trunk is a E1/R2 directly to my PBX
- No matter if caller or callee hangs up always I do have "normal clearing" message
- I know I'm receiving from my service provider the information about my releasing device, because if I use my Siemens 3800 Hipath over CSTA I can retrieve this information.

So the gold question is: How can I retrieve who is the releasing device on this situation?

Thanks in advance,
Andrew Paes

**Comment by Deantwo** [comment]
It sounds like more of a Asterisk question than a AsterNET questions. So I don't have much of an answer for you.
I would suggest asking in the Asterisk forum about what AMI event to look for.

It does look like the [ManagerEvent_Hangup](https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerEvent_Hangup) as a "cause" property, try checking that if you haven't already.

**Comment by andrew-paes** [comment]
The only way I could find after read Asterisk doc almost entirely was reading HangupRequest event messages.

HangupRequest event writes the messages like the following one:

```
Event: HangupRequest
Privilege: call,all
Channel: SIP/8103-000001be
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: 8103
CallerIDName: Agent 8103
ConnectedLineNum: 51999887766
ConnectedLineName: 51999887766
Language: en
AccountCode:
Context: from-internal
Exten: 8100
Priority: 1
Uniqueid: 1569618521.446
Linkedid: 1569618519.445
```

So accordly to [HangupRequest Event Asterisk documentation][2] I could notice the channel in the message is the channel related to the releasing device, also CallerIDNum and CallerIDName are related to.

Since I know where to read this information I download tag v1.3.0 which I was using. Then wrote a HangupRequestEvent:
```
namespace AsterNET.Manager.Event
{
    public class HangupRequestEvent : AbstractChannelEvent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="source"></param>
        public HangupRequestEvent(ManagerConnection source)
            : base(source)
        {
        }
    }
}
```

And include this on ```ManagerConnection.cs``` like:
```
public delegate void HangupRequestEventHandler(object sender, Event.HangupRequestEvent e);
public event EventHandler<HangupRequestEvent> HangupRequest;
Helper.RegisterEventHandler(registeredEventHandlers, 16, typeof(HangupRequestEvent));
```
also 
```
case 15:
	if (Dial != null)
	{
		Dial(this, (DialEvent)e);
		return;
	}
	break;
case 16:
	if (HangupRequest != null)
	{
		HangupRequest(this, (HangupRequestEvent)e);
		return;
	}
	break;
case 17:
	if (DNDState != null)
	{
		DNDState(this, (DNDStateEvent)e);
		return;
	}
	break;
```

This feature is not implemented right now on the library, but I'm going to push over there and ask them to include on next release.

Yet I don't know where to read this information on FreePBX Admin.


  [2]: https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerEvent_HangupRequest

**Comment by Deantwo** [comment]
You mean `HangupRequestEvent` isn't implemented in AsterNET?
Feel free to make a pull request with your change.

**Comment by andrew-paes** [comment]
> You mean `HangupRequestEvent` isn't implemented in AsterNET?
> Feel free to make a pull request with your change.

Yeah, it isn't. I will, but I was working on version 1.3.0 and if I branch master to do it, there are many different things from 1.3.0.

What do you recommend; branch 1.3.0 or branch master?

**Comment by Deantwo** [comment]
> What do you recommend; branch 1.3.0 or branch master?

Why not both? :woman_shrugging: 

I don't expect 2.0.0 to be released any time soon, unless we suddenly get a lot more activity here. So might be more likely to post a small update to the 1.x.x branch.
That is what #206 is asking for too, I think.

**Comment by andrew-paes** [comment]
> > What do you recommend; branch 1.3.0 or branch master?
> 
> Why not both? 🤷‍♀
> 
> I don't expect 2.0.0 to be released any time soon, unless we suddenly get a lot more activity here. So might be more likely to post a small update to the 1.x.x branch.
> That is what #206 is asking for too, I think.

Are you guys using Giit Flow to manage this repo? Cuz I couldn't see any develop branch to work on.

Are you going to create any branch to work on or I should just work on this branch https://github.com/AsterNET/AsterNET/tree/AsterNET-1.x ?

**Comment by Deantwo** [comment]
> I should just work on this branch https://github.com/AsterNET/AsterNET/tree/AsterNET-1.x ?

Yes.

**Comment by andrew-paes** [comment]
> > I should just work on this branch https://github.com/AsterNET/AsterNET/tree/AsterNET-1.x ?
> 
> Yes.

Well, I'm trying to finish my 2019 tasklist and one things is on it is this issue. So I tried to finish it now and I can't. Could you please give me rights for it?

andrew.paes@TRUE07 MINGW64 /d/Projetos/AsterNET (AsterNET-1.x)
$ git push
ERROR: Permission to AsterNET/AsterNET.git denied to andrew-paes.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Deantwo** [comment]
I am not sure what you are trying to do, but you can make a pull request when using GitHub. I have never used pure Git, so I can't help you with how you would do that. But I guess you make a fork here on GitHub and push your changes to that, then make the pull request.

**Comment by andrew-paes** [comment]
> I am not sure what you are trying to do, but you can make a pull request when using GitHub. I have never used pure Git, so I can't help you with how you would do that. But I guess you make a fork here on GitHub and push your changes to that, then make the pull request.

Yeah, I was avoiding all these steps.. A bit lazy at the end of the year lol

The only other way would be putting me as colab, but nevermind. Tomorrow I think I can do it.

Tnx,

**Comment by ddyner** [comment]
I also determine who hung up the HangupRequest event.
Added pull request #225 to fix this
