### ISSUE TITLE
Is there a way to add/edit paging groups with AsterNET?

### ISSUE THREAD

**Issue by threeeye** [AsterNET/AsterNET#209]
Hi guys, as the title states,
Is there a way to add/edit paging groups with AsterNET? (VB.NET)

**Comment by Deantwo** [comment]
Some quick google magic seem to suggest that "Paging Groups" are only defined in the dial plan, so I would assume that it is not possible to change them using the AMI.
See: https://community.asterisk.org/t/list-paging-groups/69783
