### ISSUE TITLE
Does this support Net Core 3.x?

### ISSUE THREAD

**Issue by Primtek-Dev** [AsterNET/AsterNET#213]
Does this support Net Core 3.x? , I need to implement this on Linux platform..
please advise

thanks

**Comment by Deantwo** [comment]
You can download the source and try it.

Last discussion about .Net Core suggested there was an issue, but it is not a subject I know a lot about.
See: #182

**Comment by Primtek-Dev** [comment]
@Deantwo thanks and yes, it supports Net Core 3.0, I tried it and deployed it on CentOS 7.. and working as expected.. thanks
