### ISSUE TITLE
How to hangup call with regex?

### ISSUE THREAD

**Issue by Primtek-Dev** [AsterNET/AsterNET#216]
Hi all,

I am trying to hangup a call with regex as below but it does not work (the call did not hangup), what I missed?
```C#
HangupAction hac = new HangupAction();
hac.Channel =  "/^PJSIP/1234-*$"; 
manager.SendAction(hac);
```

**Comment by Deantwo** [comment]
Interesting. I didn't actually know that regex was possible, but it is mentioned in the Asterisk doc.
See: https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+ManagerAction_Hangup

Aren't you missing a `.` in your regex? `*` along doesn't work, for a full wildcard you have to write `.*`. Also looks like you are missing the ending `/` for it to be registered as regex. Check the example in the documentation, `"/^SIP/provider-.*$/"`.
Try `"/^PJSIP/1234-.*$/"` in your code.

You can also test it on https://regex101.com/, I use that site a lot when doing regex.

**Comment by Primtek-Dev** [comment]
@Deantwo  .. thanks a lot .. you saved my time :)
