### ISSUE TITLE
Forwarding incoming call to an external phone number

### ISSUE THREAD

**Issue by jajiro** [AsterNET/AsterNET#230]
It's posible to forwarding any incoming call to an external phone number?
I have 3 telephone lines and I need to resend any incoming call to 2 differents external telephones.
The idea is to resend the incoming call to an external telephone "1" if the incoming call arrives from the first line and to an external telephone "2" if the incoming call arrives from the second line.
Is it possible?
How?
Thanks!

**Comment by Deantwo** [comment]
This sounds more like an Asterisk question than an AsterNET question.
Why are you asking here? Do you know what AMI commands to use? If not you might want to start on an Asterisk help forum instead.

**Comment by jajiro** [comment]
Sorry, I will.
