### ISSUE TITLE
Not working in Kubernetes

### ISSUE THREAD

**Issue by norcis** [AsterNET/AsterNET#232]
App works in docker running in virtual machine. But  when running in Kubernetes (Linux or Windows) it starts, but do not handle calls. PBX reports error: `No script configured for URL 'agi://10.20.54.123:30000/IVR_TEST' (script 'IVR_TEST')`

**Comment by Deantwo** [comment]
Sounds like a PBX/Asterisk issue?
Not enough information for me to know what your issue is.
