### ISSUE TITLE
AsterNet command returns only last line

### ISSUE THREAD

**Issue by marcosnegrisoli** [AsterNET/AsterNET#233]
I'm sending the command below using C # and AsterNet.

The command executes, but only returns the last line of the command's response.

``` C#
CommandAction cmdAction = new CommandAction ();
cmdAction.Command = "core show channels";
var response = manager.SendAction(cmdAction);
```

Ex:  response:  "0 calls processed"

Does anyone know how I do to return all lines of the command response?

**Comment by Deantwo** [comment]
Maybe the [`CoreShowChannelsAction`](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/Action/CoreShowChannelsAction.cs) action would be better?
Or maybe you are only getting one line because there only is one line?

**Comment by marcosnegrisoli** [comment]
The "core show channels" command is just an example. It occurs with any command that has more than 1 line.

In this example he brought the text: "0 calls processed"
 
But when running on the Asterisk console this is the return:

"asterisk*CLI> core show channels
Channel              Location             State   Application(Data)
0 active channels
0 active calls
0 calls processed"

**Comment by Deantwo** [comment]
Maybe #55 would be helpful for you?

**Comment by Deantwo** [comment]
I guess that [ManagerEvent_CoreShowChannel](https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+ManagerEvent_CoreShowChannel) hasn't been implemented still? Someone should probably just do that.

**Comment by marcosnegrisoli** [comment]
> Maybe #55 would be helpful for you?

Unfortunately it doesn't help :(

**Comment by marcosnegrisoli** [comment]
As it was marked as a BUG, and I need to give a quick fix, I changed the project.

The problem is that the command returns several lines with the key name "output". The AsterNet project uses IDictionary and it does not support keys with the same name.

I worked around the problem by adding an extension to the "output" key name. ["output_0", "output_1", ... "output_x"] It is not an elegant solution :( , but it solved the problem without having to change many things in the code.


____________________________________________
Helper.cs

        internal static void AddKeyValue(IDictionary list, string line)
        {
            int delimiterIndex = line.IndexOf(":");
            if (delimiterIndex > 0 && line.Length > delimiterIndex + 1)
            {
                string name = line.Substring(0, delimiterIndex).ToLower(CultureInfo).Trim();
                string val = line.Substring(delimiterIndex + 1).Trim();

```
                if (name == "output")
                {
                    int output_count = 0;
                    foreach (String key in list.Keys)
                    {
                        if (key.Length > 7 && key.Substring(0 , 7) == "output_")
                        {
                            output_count += 1;
                        }
                    }
                    name += "_" + output_count.ToString();
                }
```

                if (val == "<null>")
                    list[name] = null;
                else
                    list[name] = val;
            }
        }

**Comment by marcosnegrisoli** [comment]
I made a correction by changing Helper.cs 

I added this line:
 if (name == "output" && list.Contains("output")) val = list[name] + Environment.NewLine + val;


```
        internal static void AddKeyValue(IDictionary list, string line)
        {
            int delimiterIndex = line.IndexOf(":");
            if (delimiterIndex > 0 && line.Length > delimiterIndex + 1)
            {
                string name = line.Substring(0, delimiterIndex).ToLower(CultureInfo).Trim();
                string val = line.Substring(delimiterIndex + 1).Trim();

                if (name == "output" && list.Contains("output")) val = list[name] + Environment.NewLine + val;

                if (val == "<null>")
                    list[name] = null;
                else
                    list[name] = val;
            }
        }
```

**Comment by marcosnegrisoli** [comment]
Sorry for the late reply.

I'm using Asterisk 16

Before:
![image](https://user-images.githubusercontent.com/23579965/87731360-ac70f480-c7a0-11ea-8ebb-cc10b4ea9a24.png)

After:
![image](https://user-images.githubusercontent.com/23579965/87731384-bf83c480-c7a0-11ea-8bc5-b4a826e57b0f.png)

**Comment by omidsaghi** [comment]
that is great
thanks very much.
