### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by brook2006** [AsterNET/AsterNET#236]
I have seen a few messages that say AsterNET supports .Net Core, but when I try, Visual Studio informs me that it isn't. Is there something I am missing?

This is the message I am getting:

`Warning	NU1701	Package 'AsterNET 1.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.`

**Comment by Deantwo** [comment]
Duplicate of #213

**Comment by Deantwo** [comment]
Yes the NuGet version likely isn't in .Net Core. You will have to download the source and build it yourself. Other than that it should support .Net Core according to linked issue above.

There are also some change in the master branch that might be nice to have, over the 1.3.0 version that is on NuGet still.

**Comment by brook2006** [comment]
I was trying the version on NuGet. Thank you.
