### ISSUE TITLE
How to catch the call event 

### ISSUE THREAD

**Issue by alexprime100** [AsterNET/AsterNET#237]
Hi, I have to create an app that can catch the call event and get the callerID. I saw in the documentation, that the agentCalledEvent allows to get the callerID, but I didn't find any tutorials that explains how to catch an event. The only thing i succeed is to login with the ManagerConnection.
Does anyone know how to catch an event with AsterNet ?

**Comment by Deantwo** [comment]
You can check the code I posted in #132.

**Comment by alexprime100** [comment]
Thank you, I will check it now
