### ISSUE TITLE
Unknown Asterisk version 16.15.1

### ISSUE THREAD

**Issue by butunin** [AsterNET/AsterNET#250]
Hello ... 
my  Asterisk version 16.15.1

  var manager = new ManagerConnection("10.0.24.1", 5038, "ad", "7159b8aeb26e4");
   manager.Login();
   
   Error: Unknown Asterisk version 16.15.1

**Comment by Deantwo** [comment]
Ah I see now. The fix I made for this issue was never tested and checked in.
Maybe you can test the #221 code and see if it fixes the issue? Then I can check that code in finally.

**Comment by butunin** [comment]
Hello Friend ...
I do not quite understand what I need to change, if you want I can give you remote access to the system (TW) so that you can test what you need to solve this problem. Since the number of requests you will receive will increase

**Comment by Deantwo** [comment]
I was asking if you could download and test the code from https://github.com/AsterNET/AsterNET/tree/NewAsteriskVersions, to see if it fixed your issue. I assume it will.

Maybe I should just merge it.

**Comment by butunin** [comment]
> I was asking if you could download and test the code from https://github.com/AsterNET/AsterNET/tree/NewAsteriskVersions, to see if it fixed your issue. I assume it will.
> 
> Maybe I should just merge it.

404 page not found (((

**Comment by Deantwo** [comment]
> 404 page not found (((

I merged it to https://github.com/AsterNET/AsterNET/tree/AsterNET-1.x and https://github.com/AsterNET/AsterNET/tree/master, so try and see if either of those work for you.
If it works, I guess we can update the NuGet package too.

**Comment by butunin** [comment]
> > 404 page not found (((
> 
> I merged it to https://github.com/AsterNET/AsterNET/tree/AsterNET-1.x and https://github.com/AsterNET/AsterNET/tree/master, so try and see if either of those work for you.
> If it works, I guess we can update the NuGet package too.

THX! work
