### ISSUE TITLE
Is AsterNET still actively maintained?

### ISSUE THREAD

**Issue by AsterixMechant** [AsterNET/AsterNET#260]
I can't help but notice that last release occurred back in 2018. That's a really long time with no updates. Have you guys abandoned this project?

**Comment by Deantwo** [comment]
I am still here, and I read everything that is posted and such.
But I haven't really worked with Asterisk for a a couple years, and I have no test environment anymore.

I don't know if @skrusty is still around, as I was never good at using IRC for chatting.

**Comment by hugodeco** [comment]
i'm still improving asternet, follow https://github.com/sufficit/sufficit-asternet-fork, create new requests there.

**Comment by Deantwo** [comment]
@hugodeco, feel free to make pull requests to here.
