### ISSUE TITLE
Question: Is AsterNET built to support connecting to multiple AMIs?

### ISSUE THREAD

**Issue by stoyandimov** [AsterNET/AsterNET#263]
We are planning to use AsterNET in one of our new components.

My question is: Can we connect to 40 different Asterisks on different servers from the same .NET process using 40 different `ManagerConnection`s? In other words, is AsterNET safe to use to connect to multiple AMIs from the same process?

**Comment by Deantwo** [comment]
I don't see why it wouldn't work. Try it.
