### ISSUE TITLE
Getting Timeout waiting for protocol identifier error on Aster.Net login method

### ISSUE THREAD

**Issue by alirashidi1993** [AsterNET/AsterNET#264]
I have a virtual machine with issabel 4 installed on it and by default Asterisk 16 is installed as well. 
I can access asterisk CLI using Issabel console by typing `<asterisk -r>` command.

I want to connect to asterisk using AsterNet nuget package. there is a simple sample provided by AsterNet documenation. it is like this:
```C#
var mgr = new ManagerConnection("'192.168.1.100'", 5038, "'admin'", "'13700213'");
mgr.Login();
```
But every time I get this error: Timeout waiting for protocol identifier

any help is appreciated. How can I connect to asterisk in .net ?

**Comment by Deantwo** [comment]
Looks like you have an issue in your strings:
```C#
"'192.168.1.100'"
"'admin'"
"'13700213'"
```
Not sure why you have both `"` and `'` around it. But [as I wrote in the other issue thread](https://github.com/AsterNET/AsterNET/issues/134#issuecomment-371049603) that you replied to, this error will happen when you write an invalid IP-address.
> I get the same error when I type in an incorrect IP address or port number. So I suggest checking those are correct first.

Change your code to:
```C#
var mgr = new ManagerConnection("192.168.1.100", 5038, "admin", "13700213");
mgr.Login();
```
And then try again.
