### ISSUE TITLE
ManagerConnection.SuccessfulAuth does not fire

### ISSUE THREAD

**Issue by babskig** [AsterNET/AsterNET#270]
When using the code:

```
var connection = new ManagerConnection(host, port, user, pass);
connection.SuccessfulAuth += (s, e) =>
{
    Console.WriteLine("{0} In SuccessfulAuth", DateTime.Now);
};
connection.Login();
```

The event SuccessfulAuth  never fires.

I captured the TCP traffic, with the following data (with sensitive info removed):
```
Asterisk Call Manager/1.1
Action: Challenge
ActionID: 15368010_0#
AuthType: MD5

Response: Success
ActionID: 15368010_0#
Challenge: <redacted>

Action: Login
ActionID: 15368010_1#
Username: <redacted>
AuthType: MD5
Key: <redacted>

Response: Success
ActionID: 15368010_1#
Message: Authentication accepted
```

I expected that at the point the asterisk server returned "Message: Authentication accepted" the SuccessfulAuth would fire.

I tried using the nuget package version 1.3.0 and by clone this repo (HEAD was at c4df9d8ecb578460d6442f7cd673b9b11763fadd).

Attached is a minimal Visual Studio 2017 project that reproduces the issue.
[TestAsternetAuth.zip](https://github.com/AsterNET/AsterNET/files/9762193/TestAsternetAuth.zip)

**Comment by Deantwo** [comment]
What version of Asterisk are you using?

**Comment by babskig** [comment]
Running: asterisk -V
Asterisk 1.6.2.6

**Comment by Deantwo** [comment]
Asterisk 1.6 is extremely old. The `SuccessfulAuth` event was supposed added in Asterisk 13 (or 12?), so that is why the event isn't raised.

See: https://wiki.asterisk.org/wiki/display/AST/New+in+13#Newin13-Events
> AMI will now emit security events. A new class authorization has been added in manager.conf for the security events, security. The new events are:
> ...
> **SuccessfulAuth**
> Raised when a request successfully authenticates.

This will likely not be changed in AsterNET, since AsterNET is made to just convert all AMI messages it receives and little else.

**Comment by babskig** [comment]
Ah, I see. Thanks for looking.
