### ISSUE TITLE
Abandoned calls monitoring

### ISSUE THREAD

**Issue by AlexAlexKud** [AsterNET/AsterNET#273]
Hi everyone!
I need to monitor all abandoned calls. I`ve got two problems:
1) Which event I need to listen that is more suitable to catch abandoned  call?
2) If my application went offline for a while then I need to receive abandoned calls for that period. I've googled a lotm, but didn't find how to log/receive abandoned  calls from history?

I ask for advice in which direction I need to dig in, especially with second question.

**Comment by Deantwo** [comment]
By "abandoned calls", you mean calls in a queue that hung up before being taken by a queue member?
The [`QueueCallerAbandon` event](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L289) is raised when a caller abandons the queue. The [`QueueCallerAbandonEvent` object](https://github.com/AsterNET/AsterNET/blob/53b3a954a32f4b73929c27c6718006c17c77f978/Asterisk.2013/Asterisk.NET/Manager/Event/QueueCallerAbandonEvent.cs) however doesn't contain a lot of information and is probably more used to increment a counter. So you might have to be actively simulating the queue in your code, so you can keep track of which call dropped out.
To be honest, I am not completely sure that the AIM supports what you are asking for in an easy way.

As for what you would do if your application isn't running? I would assume the information might be saved in the Asterisk database somehow. But this is likely not accessible via the AMI, so you will have to ask on the [Asterisk forum](https://community.asterisk.org/) for how you might get that information out, assuming it exists.
