### ISSUE TITLE
[Bug] - `Dial` event not firing on Asterisk 18.x (maybe due to AsteriskVersion always `ASTERISK_1_0`)

### ISSUE THREAD

**Issue by ITaluone** [AsterNET/AsterNET#280]
Hi,

I am using this library to connect to an LocaPhone 5.6 instance, which under the hood is running Asterisk 18.x. 

I can successfully connect the `ManagerConnection` via phonesuite, but I miss several events (especially the `Dial` event)

With LocaPhone 4.x this worked as expected, but now it doesn't. 

Looking at the code, it should definitely be able to handle Asterisk versions up to 17.x and above.

What I am doing wrong?

**Comment by Deantwo** [comment]
Which version of AsterNET are you using? I forget which version the NuGet is on, so please double check the version of the DLL files.

There is no `ASTERISK_1_0` value in the [`AsteriskVersion` enum](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/AsteriskVersion.cs).

What is it about the [`Dial` event](https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Event_DialEvent.htm) you are missing? You mean it isn't being raised?

**Comment by ITaluone** [comment]
> Which version of AsterNET are you using?

The latest version which is 1.3.0

> There is no ASTERISK_1_0 value in the AsteriskVersion enum

I am pretty sure it has this value... 
https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/AsteriskVersion.cs#L9

And a screenshot while debugging (`ManagerConnection.AsteriskVersion`):
![image](https://github.com/AsterNET/AsterNET/assets/44049228/aef60102-b5e1-4209-92f6-aabe16974456)


> What is it about the [Dial event](https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Event_DialEvent.htm) you are missing? You mean it isn't being raised?What is it about the [Dial event](https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Event_DialEvent.htm) you are missing? You mean it isn't being raised?

Correct

**Comment by Deantwo** [comment]
> > There is no ASTERISK_1_0 value in the AsteriskVersion enum
> 
> I am pretty sure it has this value...
> 
> https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/AsteriskVersion.cs#L9

Oh, you are correct. I was looking at [`determineVersion()` method](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1030), where `ASTERISK_1_0` isn't possible unless it literally defaults to not finding the version.

Something seems to be failing in version detection, so if you can get the exact output from the `core show version` command in the Asterisk CLI, we can debug it better.

**Comment by ITaluone** [comment]
> Something seems to be failing in version detection, so if you can get the exact output from the core show version command in the Asterisk CLI, we can debug it better.

I assume that the complete command looks like this: `asterisk core show version`:

```bash
administrator@pbxserver:~$  asterisk core show version
administrator@pbxserver:~$
```

Or maybe the event has changed? Previously, We hooked into the `Dial` event to perform some actions on incoming call, like look up the internal phonebook, show notification with a suggestion of the caller, etc. etc.

**Comment by ITaluone** [comment]
Or the other way round: what purpose does this field `AsteriskVersion` have? Is it an internal switch for version specific features?

To be clear: My main problem is that the dial event isn't triggering, I assumed (since the version is also incorrect) that this could be something related, because this used to work with LocaPhone 4.x (Asterisk 1.8.x).

**Comment by Deantwo** [comment]
> > Something seems to be failing in version detection, so if you can get the exact output from the core show version command in the Asterisk CLI, we can debug it better.
> 
> I assume that the complete command looks like this: `asterisk core show version`:
> 
> ```shell
> administrator@pbxserver:~$  asterisk core show version
> administrator@pbxserver:~$
> ```

You are on the Linux CLI? I don't know how to access the Asterisk CLI from Linux, you will likely have to look at that up yourself.

> Or the other way round: what purpose does this field `AsteriskVersion` have? Is it an internal switch for version specific features?

As you can see in the [`determineVersion()` method](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1030), it is setting the `VAR_DELIMITER` value. This is for backward compatibility with older version of Asterisk, but it defaults to the old value if it cannot detect the version as being newer.

Specifically it should be caught in the [`else if (version.IndexOf('.') >= 2)` case](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1098), but I guess I didn't test that good enough and it is failing.

**Comment by ITaluone** [comment]
> To be clear: My main problem is that the dial event isn't triggering, I assumed (since the version is also incorrect) that this could be something related, because this used to work with LocaPhone 4.x (Asterisk 1.8.x).

Is this related? Or should I open a new ticket for this?

**Comment by ITaluone** [comment]
> > > Something seems to be failing in version detection, so if you can get the exact output from the core show version command in the Asterisk CLI, we can debug it better.
> > 
> > 
> > I assume that the complete command looks like this: `asterisk core show version`:
> > ```shell
> > administrator@pbxserver:~$  asterisk core show version
> > administrator@pbxserver:~$
> > ```
> 
> You are on the Linux CLI? I don't know how to access the Asterisk CLI from Linux, you will likely have to look at that up yourself.

yes, I am on the linux cli. the actual command looks like this: `asterisk -rx 'core show version'`, but running this outputs this:
`Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)`

Since this file exists, but have different permissions I run `sudo -u asterisk asterisk -rx 'core show version'` which finally returns
`Asterisk 18.10.1~uloca-focal1 built by root @ pbuilder-neu on a x86_64 running Linux on 2023-06-27 07:22:17 UTC`

**Comment by ITaluone** [comment]
I seems like there was a change somewhere around the `Dial` event? Because if I change it to `DialBegin` it works like it did before.

**Comment by Deantwo** [comment]
> I seems like there was a change somewhere around the `Dial` event? Because if I change it to `DialBegin` it works like it did before.

Likely nothing has changed in the `Dial` event. Might need to implement `DialBegin` though. I am not too sure.

But if AsterNET is failing to detect the Asterisk version, the expected delimiter for the API communication will be wrong. If the wrong delimiter is used, a lot of stuff breaks down in the communication layer.

**Comment by ITaluone** [comment]
Ok, what about setting the delimiter manually via `VAR_DELIMITER` char array?

e.g. 
```csharp
_managerConnection = new ManagerConnection(Settings.Host, Settings.Port, Settings.User, Settings.Password)
{
     VAR_DELIMITER = [',']
};
```

**Comment by Deantwo** [comment]
> Ok, what about setting the delimiter manually via `VAR_DELIMITER` char array?
> 
> e.g.
> 
> ```cs
> _managerConnection = new ManagerConnection(Settings.Host, Settings.Port, Settings.User, Settings.Password)
> {
>      VAR_DELIMITER = [',']
> };
> ```

Try it and see if it fixes your other issues. If it doesn't then you can make a separate bug report about that.

**Comment by ITaluone** [comment]
> Try it and see if it fixes your other issues. If it doesn't then you can make a separate bug report about that.

Other issues? My **only** issue was that the `Dial` event wasn't triggering anymore, so I went on a debugging journey and discovered, that the `AsteriskVersion` is equal to what's actually wrong. 
(Btw.. if the `Dial` event is working as expected I just don't care what version is detected 😉)
Then I thought that this could be the issue which is leading to my main issue.

After that I fiddled around a bit with other events (which interestingly are working) and tried them to workaround my issue. And finally I tried `DialBegin` which works like the `Dial` event on LocaPhone 4.x.

PS: if I rethink about this ticket.. I made a perfect example of a [xy-problem](https://xyproblem.info/). Sorry about that 🤦‍♂️

**Comment by Deantwo** [comment]
It might help if you can debug the [`determineVersion()` method](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1030). I sadly don't have a setup I can test this on myself.

I am unsure if the [`core show version` action](https://github.com/AsterNET/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1033) is even returning a response.

**Comment by ITaluone** [comment]
I see what I can do..

**Comment by ITaluone** [comment]
Ok, in a testproject I receive the following after https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1033

![image](https://github.com/AsterNET/AsterNET/assets/44049228/524dd54c-c911-475f-96c2-321d189fb8ce)

But then it skips the `if` statement below. 

What I don't get is: Why? This is the same pattern as `if (exception is MyDerivedException)` and should work..

And this is the same for the next command and `if` statement, which leads to `ASTERISK_1_0`.

**Comment by Deantwo** [comment]
There seems to be an issue with the type of the returned object. Since it would only fail that `if` statement if the type isn't a `CommandResponse` class.

I wonder if it is related to #258.

**Comment by ITaluone** [comment]
Just for the record: my test project is .NET7.0, my "real" project .NET8.0, and with .NET6.0 it isn't working either (despite what this https://github.com/AsterNET/AsterNET/issues/258#issuecomment-1210866358 says)..

**Comment by ITaluone** [comment]
I could try to give this a shot, but **only** if the PR gets attention (like many other open PRs...).

**Comment by Deantwo** [comment]
> I could try to give this a shot, but **only** if the PR gets attention (like many other open PRs...).

If the pull request isn't so complicated that it needs a lot of testing, sure.

**Comment by ITaluone** [comment]
Ahm.. I cloned the latest master and tried this with a .NET8.0 test project.. This works and correctly returns `ASTERISK_Newer`

Then I installed latest (1.3.0) and there it fails.

Afterwards I compiled a local nuget package with a different version, and this also works.. 

I cannot tell whats the difference, because the code in question is the same in 1.3.0 and latest master.

**Comment by Deantwo** [comment]
If it is fixed in the `master` branch, then I guess it isn't an issue anymore.

If you can test if the `master` branch works ok otherwise, maybe we should just release it already. The main issue we have is the lack of testers.

**Comment by ITaluone** [comment]
hmm sort of :)

In my test project it detects the correct asterisk version, but in my "real" project it detects `Unknown` which is even more interesting, because this only can happen, if the `determineVersion()` is skipped. 

Edit: this must have something to do with passing a `ManagerConnection` around via DI. I instantiate a `ManagerConnection` with nothing more than `var connection = new()`, after that I adding it to DI container as singleton with `builder.Services.AddSingleton(connection)`. 

A bit later in the chain (after app startup) I do `@inject ManagerConnection Connection` and perform the login `Connection.Login()`. This leads to `AsteriskVersion.Unknown`.

But: when I do this:
```csharp
public static void DetermineVersion(this ManagerConnection connection)
{
    connection.GetType().GetMethod("determineVersion", BindingFlags.NonPublic | BindingFlags.Instance)?
        .Invoke(connection, []);
}
```
```csharp
Connection.Login(); // Version unknown
Connection.DetermineVersion(); // Version correct: 18.10.1 / AsteriskVersion.Newer
```

it works..

**Comment by Deantwo** [comment]
So then what is the issue? I am not sure I understand what you are describing.

Are you just saying that it works if you use the method after a little while? Or a second time?

**Comment by ITaluone** [comment]
I think this can be closed, if a new version is released with the state of current master..
I use a version compiled from master and it works now in production since june...

**Comment by Deantwo** [comment]
Yeah, we really should just release the master branch as a NuGet update.

The main issue is that I no longer even have a setup or a program to test it in myself.
