### ISSUE TITLE
CommandAction and CommandReponse/ManagerResponse

### ISSUE THREAD

**Issue by dleventidis** [AsterNET/AsterNET#282]
Hi,

i'm trying to send a sip show peers command with the following code:

Dim cmdAction As New CommandAction("sip show peers")
Dim s As ManagerResponse = dmanager.SendAction(cmdAction)

But at s i'm getting only the following result:

![image](https://github.com/user-attachments/assets/58b59bbb-f914-480f-98aa-c8d638ac19c2)

is it a bug? or i'm doing something wrong?

Regards

**Comment by Deantwo** [comment]
What is your Asterisk version? What is your AsterNET version?

**Comment by dleventidis** [comment]
Asterisk: 16.30.1 
I have tried using (via nuget) both asternet 1.3.0 and asternet.netstandard 2.2.1 with the same results

**Comment by Deantwo** [comment]
Use the master from this GitHub repo, the NuGet package hasn't been updated for awhile and doesn't fully work with newer versions of Asterisk.

See if that fixes your issue.

Other than that, you should probably find an Asterisk AMI command to get the peers list, rather than trying to use an Asterisk CLI command to get it. Since the CLI commands likely don't give a nice output.

**Comment by dleventidis** [comment]
thanks i'll try

**Comment by Deantwo** [comment]
The [`SIPpeers` AMI command](https://docs.asterisk.org/Asterisk_16_Documentation/API_Documentation/AMI_Actions/SIPpeers/) seems to be what you want.

Subscribe to the [`PeerEntryEvent` event](https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Event_PeerEntryEvent.htm) and the [`PeerlistCompleteEvent` event](https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Event_PeerlistCompleteEvent.htm). Then use the [`SIPPeersAction` command](https://asternet.github.io/AsterNET/html/T_AsterNET_Manager_Action_SIPPeersAction.htm) to make the Asterisk send the list.

**Comment by dleventidis** [comment]
thanks for the help. (i tried to use the master -download and compile with vs 2022 but i didn't succeed)

**Comment by dleventidis** [comment]
finally i managed t obuild the asternet from the master. And it does work!

Thanks in advance

Regards
