### ISSUE TITLE
QueueAddAction on all queues

### ISSUE THREAD

**Issue by dleventidis** [AsterNET/AsterNET#285]
Hi, 
is it possible to add a member (via QueueAddAction) in all the queues of the system? (what to i have to specify as queue)

Thanks

**Comment by Deantwo** [comment]
Here is the Asterisk16 documentation for the AMI action: https://docs.asterisk.org/Asterisk_16_Documentation/API_Documentation/AMI_Actions/QueueAdd/
Simce, again, the Asterisk11 documentation doesn't exist on the official site anymore.

I used this very little in my own project back in the day, and never in production, so I don't know much about it.

I assume you have to make it join one queue at a time, but I suggest you just try it out and see what you can do. Or you can ask on the Asterisk forums.

**Comment by dleventidis** [comment]
Thanks for the help. I'm looping between queues as you proposed. It seems ok.

Regards
