### ISSUE TITLE
asterisk 11.25.3 is QueueCallerJoinEvent available?

### ISSUE THREAD

**Issue by dleventidis** [AsterNET/AsterNET#286]
Hi,
i'm trying to get QueueCallerJoinEvent on an asterisk v 11.25.3 (using branch/compiled asternet 1.3.0 library) but the event is not raised.

also the QueueCallerAbandonEvent (which is raised is completely different. 

Can you please help?

Regards

**Comment by Deantwo** [comment]
You are using a very old version of Asterisk.

You have to use the `JoinEvent`, if I remember correctly. In >=Asterisk12, the event was renamed to  `QueueCallerJoinEvent`. I forget how easily we made it backwards compatible here, but I believe one inherit from the other to make it easier on you. You likely just have to be sure that you are subscribing to both events.

See: https://github.com/AsterNET/AsterNET/pull/127#issuecomment-353377322

The `QueueCallerAbandonEvent` is not very reliable. It is mostly just used to increment a counter, so you can make some shaky statistics on how many callers hangup before being answered by a member.

You might be looking for `LeaveEvent` and `QueueCallerLeaveEvent` instead.

**Comment by Deantwo** [comment]
Subscribe like this, to make it compatible with both versions of Asterisk:
``` csharp
_ami.Join += Monitoring_QueueCallerJoin; // < Asterisk12
_ami.Leave += Monitoring_QueueCallerLeave; // < Asterisk12
_ami.QueueCallerJoin += Monitoring_QueueCallerJoin; // >= Asterisk12
_ami.QueueCallerLeave += Monitoring_QueueCallerLeave; // >= Asterisk12
```

**Comment by dleventidis** [comment]
you saved my life once more :).


Thanks.

**Comment by dleventidis** [comment]
Hi,

i have the same issue with the agentconnect event which is not raised (same versions)

Thanks
