### ISSUE TITLE
Asterisk Version regex not matching Asterisk 13

### ISSUE THREAD

**Issue by JobaDiniz** [AsterNET/AsterNET#38]
The regex `^Asterisk\\s+\\D*([0-9]+.[0-9]+.[0-9]+|[1-9][0-9]-r[0-9]+).*$` is not matching the following:
`Asterisk certified/13.1-cert4 built by root @ cubietruck on a armv7l running Linux on 2016-02-17 18:57:29 UTC`

Therefore, when sending an `OriginateAction` with *variables* they are not separated correctly:

```
var action = new OriginateAction();
//code...
action.SetVariable("VAR1", "value1");
action.SetVariable("VAR2", "value2");
```

**Comment by skrusty** [comment]
It does match version 13, just not 13 certified.

**Comment by skrusty** [comment]
Did you look to fix the regex?

**Comment by JobaDiniz** [comment]
The project is *paused* right now, I'm focus on another thing. However, I don't know what are the other *"string versions"* so I don't break the other comparisions.
If you could share, then when I get back to the project, I'll create some unit tests to make sure every string passes.

**Comment by skrusty** [comment]
Unit Tests are something we need for this project, although i suspect the way the API works right now, unit testing a lot of the code could be quite difficult. 

Open to suggestions though.

**Comment by albertmata** [comment]
I did modify the regex to allow for certified versions.
The new regex is:
`        public static Regex ASTERISK_VERSION = new Regex( "^Asterisk\\s+\\D*([0-9]+.[0-9]+.[0-9]+|[1-9][0-9]-r[0-9]+|[0-9]+.[0-9]+-cert[0-9]).*$", 
                    RegexOptions.Compiled | RegexOptions.IgnoreCase);`

**Comment by skrusty** [comment]
#51
