### ISSUE TITLE
ManagerConnection BuildAction bug

### ISSUE THREAD

**Issue by albertmata** [AsterNET/AsterNET#50]
I had to rewrite this method because of a null pointer exception at the end of the method. The actionVar.GetVariables can return null.

New code:

IActionVariable actionVar = action as IActionVariable;
if(actionVar != null )
            {
                var variables = actionVar.GetVariables();
                if ( variables != null && variables.Count > 0 )
                {
                    sb.Append( string.Concat( "Variable: ", Helper.JoinVariables( actionVar.GetVariables(), VAR_DELIMITER, "=" ), Common.LINE_SEPARATOR ) );
                }
            }

**Comment by skrusty** [comment]
If you would be so kind as to create a pull request? That would be the quickest way for us to review and include your patch in the master branch.

**Comment by albertmata** [comment]
I'm sorry, I don't know how to do that, I've never worked with git. I just
downloaded the code as a zip.

El dv., 18 març 2016 a les 10:03, Ben Merrills (<notifications@github.com>)
va escriure:

**Comment by skrusty** [comment]
If you're using Visual Studio, you can open a github repo directly from visual studio.

http://rickrainey.com/2013/07/27/visual-studio-and-gitub-the-basics-of-working-with-existing-repositories-2/

This might help (i did a quick google). Having your contributions as a pull request would make life a lot easier. 

Thanks again.

**Comment by albertmata** [comment]
Ok, I've followed the steps described in the link you sent me.
I've forked the repo.
I've cloned this forked repo.
I've commited the changes locally.
But, when I try to synchronize either with VisualStudio or GitHub GUI it
fails.

El dv., 18 març 2016 a les 10:31, Ben Merrills (<notifications@github.com>)
va escriure:

**Comment by skrusty** [comment]
IS there an error?

**Comment by albertmata** [comment]
It seems a timeout error, i Will try to follow the steps again.

**Comment by albertmata** [comment]
Now I could push the changes to my repo and create a pull request.
Thanks for the link, I've learned something new today. :)


El dv., 18 març 2016 a les 16:28, Albert Mata Viñuales (<
albertmata@gmail.com>) va escriure:

**Comment by skrusty** [comment]
Will review #51 tomorrow.
