### ISSUE TITLE
Asterisk UniqueID

### ISSUE THREAD

**Issue by xiron3** [AsterNET/AsterNET#62]
Hi,

I have a question regarding Asterisk and AsterNET. I am writing application to control call flow. I have Asterisk 12.
In my application I have a List of current calls. I match my calls with AsterNET events by UniqueID attribute. For example in Originate response I have UniqueID = 1460280786.134 then I am cutting .134 from this number and save to my Call object. The number of 1460280786 becomes my UniqieID of call. I know that UniqueID is identifier of channel not call in Asterisk so in my call object I have List of ChannelUniqueID. 

The problem: Sometimes asterisk changes UniqueID (the number before "." without no reason).
Standard (correct log flow):
![image](https://cloud.githubusercontent.com/assets/18175529/14409446/c624f96c-ff13-11e5-971f-a3eb207b07e4.png)

Wrong log flow:
![image](https://cloud.githubusercontent.com/assets/18175529/14409443/bfdcfaa0-ff13-11e5-8b10-20c35c6ca3dd.png)

As You can see in the second call flow asterisk send Originate Response with UniqueID=1460280786.134 and after that sends events with UniqueID="1460280787.136".

Of course I know that the UniqueID can be changed for example after transfer the call 
I am surprised that UniqueID is changing during one simple outgoing call.

Plis help :)
Regards 
Peter

**Comment by skrusty** [comment]
Doesn't sound right. I will look at some of my Originate code and see how I expect it to flow and come back to you.

**Comment by xiron3** [comment]
@skrusty I would be very gratefull.
I'm looking forward for you code samples. 

Regards
Peter

**Comment by xiron3** [comment]
@skrusty I renew my request for examples of event handling of calls.
My company expects results in two weeks and I'm stuck in this problem. 
Plis help .It will be the perfect gift for my birthday, which I have today :)

Regards 
Peter

**Comment by skrusty** [comment]
The UniqueId should not change unless the channel changes. I think you need to that this issue up in the Asterisk forums, as I can't see why the behaviour your seeing should happen.

forums.asterisk.org

Sorry
