### ISSUE TITLE
For few calls No event is firing after NewStateEvent ( Dialing & Ringing)

### ISSUE THREAD

**Issue by pradeepWritso** [AsterNET/AsterNET#64]
Hi,
I'm developing an application in C# by using AsterNET to originate calls and its works fine,
My problem is that for few calls No event (hangup, cdr, etc) is firing after NewStateEvent ( Dialing & Ringing).

I have two question:
1) Is there any event that must fire,  no matter call is connected or not?
2) How can I ensure that call is disconnected now?

Thnaks in advance.

**Comment by skrusty** [comment]
You should be seeing those events if Asterisk is sending them. Have you checked the debug console to see if those events were received at all?

**Comment by k07** [comment]
hii pradeep .I am facing same issues.If you solved can you please share me the solutions.
