### ISSUE TITLE
Call hangup issue

### ISSUE THREAD

**Issue by k07** [AsterNET/AsterNET#66]
I orginate calls in AsterNet and its works fine but Call Suddenly hang up  

this is my  output console 
  "       Received response: "200 OK" from '1005' without SDP
    -- Executing [1005@from-internal:1] Dial("SIP/1005-00000000", "") in new 
  == Spawn extension (from-internal, 1005, 1) exited non-zero on 'SIP/1005-00000000'
    -- Executing [h@from-internal:1] Hangup("SIP/1005-00000000", "") in new stack  "

my dialplan section
[ Context 'from-internal' created by 'pbx_config' ]
  '1004' =>         1. Dial()                                     [pbx_config]
  '1005' =>         1. Dial()                                     [pbx_config]

After Orginate Call a new State event is fired.then how can handle that call ?.Sorry if i made any mistakes bcoz i am new in Asterisk and AsterNet.

**Comment by skrusty** [comment]
Sudden hangups sound like a problem in Asterisk more than AsterNET, especially if the Originate worked.

Might be worth setting the debug in Asterisk Console and looking for something that gives a reason as to why the call is being hungup!

https://wiki.asterisk.org/wiki/display/AST/Collecting+Debug+Information
