### ISSUE TITLE
How to transfer call to any agent (decide on run time) after answer by client.

### ISSUE THREAD

**Issue by pradeepWritso** [AsterNET/AsterNET#67]
Hi,
I'm developing an application in C# by using AsterNET to originate calls by following method and its works fine. I provide clientPhoneNo & agentExtensionNo at OriginateAction. 
 var oc = new OriginateAction
            {
                Context = _pbxSetting.Context,
                Priority = "1",
                Channel = $"{_pbxSetting.Channel}{clientPhoneNo}", 
                CallerId = clientPhoneNo,
                Exten = agentExtensionNo, 
                Timeout = _pbxSetting.Timeout, 
                Async = true
            };

Is there any way that:
1) After client answer call 
2) I decide a agent by my algorithm
3) and transfer call to that agent (I decide by algorithm). 

Please let me know your thoughts.

Thanks in advance.

**Comment by skrusty** [comment]
1. Answer the call depends on the SIP phone/client you're using. This isn't something you can directly do via AsterNET (Asterisk doesn't provide a default way to force a phone to answer the call). However, it can be done by sending come custom SIP headers to *some* phones.
2. app_queue provides no way of overriding the default distribution algorithm, if you want to implement your own logic in a queue, i suggest you look at maybe writing your own (using AsterNET.ARI maybe?)
3. You can force a call to be transferred to another extension. (http://www.voip-info.org/wiki/view/Asterisk+manager+Example:+Transfer)

**Comment by pradeepWritso** [comment]
Hi, 
First of all a big thanks for your reply.

I think conversation is move to wrong direction... My question was:
 Is there any way that After client answer call I decide a agent by my algorithm and transfer call to that agent (I decide by algorithm), 
means I don't want to provide agent extension no at initial of call OriginateAction I want to provide after client answer the call.

**Comment by skrusty** [comment]
If you are not using a Queue, then yes, but it's not simple.

1. You need to Originate a call to the callee
2. You need to put that call somewhere in Asterisk (?) once the Originate completes
3. You need to then transfer that call to some destination (Agent/Extension etc) based on your own logic

AsterNET will help you to do those things, but the actual way you do it is outside of the scope of AsterNET. 

If you didn't want your own distribution method for the calls, you could simple do
1. Originate call
2. Place call in queue
3. Allow queue to handle distribution

However, as you want to override step 3, which app_queue doesn't allow, you need to handle both steps 2 and 3 yourself.

One suggestion is create an Async AGI that holds the call while you decide where to send it!

**Comment by pradeepWritso** [comment]
Hi Ben,

I have to discuss some thing about above solution May I have your Skype ID or any MI ID, or may you contact me at pradeep@successivesoftwares.com

**Comment by rsalas2017** [comment]
Hi Ben:

How are you? You found a solution to this problem ?, I want to do the same. Could you give me some idea please?
regards

**Comment by skrusty** [comment]
My suggestion would be use ARI not AMI/AGI. It gives you far more control over call control.
