### ISSUE TITLE
Events delay

### ISSUE THREAD

**Issue by VsevolodGavrilov** [AsterNET/AsterNET#69]
I develop an application that dials a big list of phone numbers to determine if it available or not. The algorithm is:
1. Start separate thread for each campaign. 
2. Originate calls on 1 extension which is connected to pjsua softphone with max_calls = 1000. So the softphone can recieve 1000 simultaneous calls. I don’t think this is the best way to make a large number of simultaneous calls, but I didn’t find any other way to originate an outgoing call without extension connected to softphone. **Do you have any advice to improve this part?**
3. Monitoring NewState event. When it receives e.ChannelState = 6 the program marks the phone number as available and hangs it up
4. If during 30 sec there is no NewState event with e.ChannelState = 6 the program marks the phone number as unavailable and hangs it up

**The problem is** that there is a big delay (15-45 sec) in receiving NewState event after I take up the phone. To test the problem I have run a separate Asterisk.Net application which monitors all Asterisk events, and there is no such delays in any event. The NewState event appears exactly when I take up the phone.
Also I have tried to separate ManagerConnection instances: one for sending actions and one for receiving event. The result was the same.
And also i have tried to run application without a first step. So there was no additional threads. The result was the same too.

Here is my custom log:
12:17:09=> Hangup. SIP/myTrunk-00000168
12:17:09=> Answer. SIP/myTrunk-00000168: XXXXXXXX2 --the actual answer was at 12:16:25
12:17:09=> Hangup. SIP/myTrunk-00000167
12:17:09=> Answer. SIP/myTrunk-00000167: XXXXXXXX1 --the actual answer was at 12:16:30
12:16:46=> Hangup. SIP/108-00000166
12:16:46=> Hangup. SIP/108-00000165
12:16:19=> Call. SIP/108: XXXXXXXX2
12:16:18=> Call. SIP/108: XXXXXXXX1

**Comment by skrusty** [comment]
Hi,

Not sure I understand step 2, seems like sending 1000 calls to a softphone is asking for trouble. If you want to break down your reason a bit more, it might help to understand. I.e. is it some way of putting calls into the system just to monitor their state? If so, there are other options like using a FastAGI maybe to hold the call?

With regards to event delay:

1. Could you confirm if the delay is present on the wire (i.e. from Asterisk to you, maybe check using wireshark?)
2. The seperate app, was that using AsterNET too? If so, was that running at the same time as you were placing 1000's of calls?
3. Could this be blocking in the event queue? AsterNET pushes all it's events out on the same thread. If you block that thread, then you get a delay in pushing the events out to your code. 2 options here.
a. You set the ManagerConnection to use ASync. This will fire off each event on it's own thread! This may be overkill.
b. You put all your events into a queue and then have a separate thread pool which pulls events off the queue.

Let me know how you get on.
Ben

**Comment by VsevolodGavrilov** [comment]
Thank you for your quick response. 

About step 2. My task is… I have a database of 10 000 phone numbers and I need to define which number is available and which is not. To do so I originate calls in cycle and then listen NewState event to identify if call is answered (State = 6). And if so I hang up the call. I decided to send all calls to a softphone because I didn’t find any other way to originate the calls without Exten property.

Answers on your question about delay:
1.	It took a while to install and figure out how to use Wireshark. And now, yes – I confirm the problem is not on Astersik site. Asterisk send events exactly on time.
2.	Yes this app uses AsterNet. And one moment – I test only simultaneous 3 calls, not 1000. My goal is about 100-200 simultaneous calls
3.	I’ve already set to true the UseASyncEvents property. And it hasn’t solved the problem. I don’t think I should place events into a queue, because AsterNet have to manage 3 simultaneous calls without any additional workaround. Besides this, I don’t know how exactly to do it with AsterNet -)

**Comment by VsevolodGavrilov** [comment]
Please answer my question. The delay still occurs. I've changed the code following your last answer.

`private void LogIn()
        {
            if (isLoggedIn) return;
            
            managerSendAction = new ManagerConnection(server, port, account, password);
            managerSendAction.NewState += manager_NewState;
            managerSendAction.OriginateResponse += manager_OriginateResponse;
            managerSendAction.UseASyncEvents = true;
            managerSendAction.Dial += managerSendAction_Dial;
            managerSendAction.UserEvents += managerSendAction_UserEvents;

            try
            {
                managerSendAction.Login();

                isLoggedIn = true;
            }
            catch (Exception ex)
            {
                isLoggedIn = false;
                managerSendAction.Logoff();
            }
        }

//The algorithm originate calls in the queue (5 at a time)
private void Call(Log LogInstance)
        {
            LogIn();

            LogEvent("Call. " + dialerChannel + ": " + LogInstance.b_tel_1, null);

            var action = new OriginateAction();
            action.Channel = dialerChannel;
            action.Context = "gen-out";
            action.Exten = LogInstance.b_tel_1;
            action.Priority = "1";
            action.Async = true;
            action.Timeout = 3000;
            action.CallerId = "Keglya Contact";
            action.ActionId = LogInstance.l_asteriskActionId.ToString();

            SendAction(action, 30000, LogInstance);
        }

private void SendAction(ManagerAction action, int timeout, Log LogInstance)
        {
            try
            {
                if (timeout > 0)
                {
                    manager.SendAction(action, timeout);
                }
                else
                {
                    manager.SendAction(action);
                }
            }
            catch (Exception ex)
            {
                //some work
            }
        }
void manager_OriginateResponse(object sender, OriginateResponseEvent e)
        {
            System.Threading.ThreadPool.QueueUserWorkItem(new System.Threading.WaitCallback(OnOriginateResponse), e);
        }
private void OnOriginateResponse(object eventinfo)
        {
            OriginateResponseEvent e = (OriginateResponseEvent)eventinfo;
		//Catch only calls originated by the algorithm
            var _logs = Log.Where(l => l.l_asteriskActionId.ToString() == e.ActionId);

            if (_logs.Count() == 0) return;

            var _log = _logs.First();

            _log.l_asteriskUniqueId = e.UniqueId;
            _log.l_asteriskChannelId = e.Channel;

        }

void managerSendAction_Dial(object sender, DialEvent e)
        {
            System.Threading.ThreadPool.QueueUserWorkItem(new System.Threading.WaitCallback(OnDial), e);
        }

private void OnDial(object eventinfo)
        {
            DialEvent e = (DialEvent)eventinfo;
		
		//Catch only calls originated by the algorithm
            var _logs = Log.Where(l => l.l_asteriskUniqueId == e.UniqueId);

            if (_logs.Count() == 0) return;

            var _log = _logs.First();

            
            if (e.SubEvent == "Begin")
            {
                LogEvent("Dial. " + _log.b_tel_1, null);

                //some work
            }
            else if (e.SubEvent == "End" && e.DialStatus != "ANSWER")
            {
                LogEvent(e.DialStatus + ". " + _log.b_tel_1, null);

                //some work
            }
        }
`

The output is:
12:16:22=> Dial. 88124906750
12:16:20=> Dial. 88123706693
12:16:15=> Dial. 88123277718
12:16:14=> Dial. 88124540401
12:16:10=> Dial. 88124769290
12:16:03=> Call. Local/1@parking: 88124906750
12:16:03=> Call. Local/1@parking: 88123277718
12:16:03=> Call. Local/1@parking: 88123706693
12:16:03=> Call. Local/1@parking: 88124540401
12:16:03=> Call. Local/1@parking: 88124769290

There is a 20 sec delay between OriginateResponce event and last dial Event. And there is no any kind of delay in Wireshark.

**Comment by VsevolodGavrilov** [comment]
up

**Comment by VsevolodGavrilov** [comment]
up

**Comment by VsevolodGavrilov** [comment]
up
