### ISSUE TITLE
How to match who made a call and who received

### ISSUE THREAD

**Issue by marekbigaj** [AsterNET/AsterNET#71]
Hi,
I have a huge problem in the following scenario. I connect to the asterisk. Then I want to filter only these calls which are to number *550. I use newstate event to check if somebody is calling. But in incomming calls I see only caller number and I don't know how to check where this person wanted to call. Please helper me. I spent a lot of time trying to figure it out.

**Comment by skrusty** [comment]
Have you looked at AstTray project (https://github.com/skrusty/asttray)? It's a good reference for some simple things like this.

Have a look at how it matches incoming calls to the extension assigned to the AstTray instance (it's a simple call pop tool for windows).

**Comment by marekbigaj** [comment]
I've checked it and when I run this app in newState event handler in ringing Channel State e.Connectedlinenum is null and link event handler have never occurred. Honestly I have no idea how to use it.

**Comment by skrusty** [comment]
What version of Asterisk?

**Comment by marekbigaj** [comment]
1.6.2.11

2016-09-07 20:18 GMT+02:00 Ben Merrills <notifications@github.com>:

**Comment by skrusty** [comment]
I would suggest upgrading. e.ConnectLineNum doesn't work in 1.6
