### ISSUE TITLE
Telnet

### ISSUE THREAD

**Issue by Spmoolman** [AsterNET/AsterNET#75]
Hi,
I created a service and using the Asternet nugget. Everything works fine, but there are some issues with telnet. It is still fine when connecting to the service, but as soon as I close the telnet connection the service stops. 
This is the error occured: 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at AsterNET.FastAGI.AGIConnectionHandler.Run()
   at AsterNET.Util.ThreadTask.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Please assist?

**Comment by skrusty** [comment]
telnet? Sorry, what do you mean?

Why are you telnet'ing to the FastAGI server?

**Comment by skrusty** [comment]
The only time i've seen that error before is in this issue: https://github.com/AsterNET/AsterNET/issues/1

**Comment by Spmoolman** [comment]
Our Systems Administrators use telnet to check if the service is still running. The services is a windows service that was written using dotnet. 

I downloaded the source code, instead of using the nugget I installed from Visual Studio's Nugget Manager, and it seems to be working fine now.

**Comment by Spmoolman** [comment]
System Administrators often use TelNet to test whether a TCP socket is active (often while troubleshooting).

After downloading the source code, I found the error in AGIConnectionHandler.cs

Basically request.Request.Count was 0. Causing issues a little later when making use of the request variable.
Fixed code below: 

        public void Run()
        {
            try
            {
                var reader = new AGIReader(socket);
                var writer = new AGIWriter(socket);
                AGIRequest request = reader.ReadRequest();

                //Added check for when the request is empty
                //eg. telnet to the service 
                if (request.Request.Count > 0)
                {
                    var channel = new AGIChannel(writer, reader, _SC511_CAUSES_EXCEPTION, _SCHANGUP_CAUSES_EXCEPTION);
                    AGIScript script = mappingStrategy.DetermineScript(request);
                    Thread.SetData(_channel, channel);

                    if (script != null)
                    {
                        #if LOGGER
                            logger.Info("Begin AGIScript " + script.GetType().FullName + " on " + Thread.CurrentThread.Name);
                        #endif
                        script.Service(request, channel);
                        #if LOGGER
                            logger.Info("End AGIScript " + script.GetType().FullName + " on " + Thread.CurrentThread.Name);
                        #endif
                    }
                    else
                    {
                        var error = "No script configured for URL '" + request.RequestURL + "' (script '" + request.Script +
                                    "')";
                        channel.SendCommand(new VerboseCommand(error, 1));
                        #if LOGGER
                            logger.Error(error);
                        #endif
                    }
                }
                else
                {
                    var error = "A connection was made with no requests";
                    #if LOGGER
                        logger.Error(error);
                    #endif
                }
            }
            catch (AGIHangupException)
            {
            }
            catch (IOException)
            {
            }
            catch (AGIException ex)
            {
                #if LOGGER
                    logger.Error("AGIException while handling request", ex);
                #else
				    throw ex;
                #endif
            }
            catch (Exception ex)
            {
                #if LOGGER
                    logger.Error("Unexpected Exception while handling request", ex);
                #else
				    throw ex;
                #endif
            }

            Thread.SetData(_channel, null);
            try
            {
                socket.Close();
            }
            #if LOGGER
                catch (IOException ex)
                {
                    logger.Error("Error on close socket", ex);
                }
            #else
			    catch { }
            #endif
        }

**Comment by skrusty** [comment]
Feel free to make a pull request with your fix.

**Comment by Spmoolman** [comment]
Cool, can you perhaps give guide lines on how to create a pull request
