### ISSUE TITLE
Enable/Disable features (DND, FM, CW) from AsterNet

### ISSUE THREAD

**Issue by zbriggs** [AsterNET/AsterNET#80]
Is it possible to enable or disable features through AMI via AsterNet? I can't seem to figure out how to go about doing this and I have been pouring through AMI examples to get any hint of it I can. Is it possible through AMI? Is it possible to do it with AsterNet? Does anyone have an example?

Any help would be sincerely appreciated.

**Comment by herman1vdb** [comment]
Hi @zbriggs 

I don't know much about enabling or disabling features, but maybe you can have a look at asterisk CLI.
You should be able to create a `CommandAction` to execute a shell command as follow.

    CommandAction a = new CommandAction("core show help");
    if (manager != null)
    {
        ManagerResponse response = manager.SendAction(a, 1000);
        Console.WriteLine(response.ToString().Replace(";", Environment.NewLine));
    }

**Comment by skrusty** [comment]
Enable/Disable what features? Can you give an example of what it is you're trying to do please?

**Comment by skrusty** [comment]
Sorry, just re-read the title. Those are phone features, and not Asterisk features.

You may be able to send custom SIP notifications to the phone to enable and disable those features, but that depends on the phone, not asterisk.

**Comment by zbriggs** [comment]
If those are phone side features then how does it work to enable and disable them via FreePBX?

**Comment by skrusty** [comment]
Best asking the people who wrote freepbx? Maybe it's down to the way they've created the extension.conf etc. THere could be lots of ways.
