### ISSUE TITLE
RedirectAction Async?

### ISSUE THREAD

**Issue by Deantwo** [AsterNET/AsterNET#86]
I am trying to send a `RedirectAction` to the Asterisk server, but I am getting some timeout exceptions.
``` csharp
ManagerResponse redirectResponse = myManagerConn.SendAction(new RedirectAction()
{
    Channel = channel,
    Exten = sip,
    Context = _context,
    Priority = 1
});
```

With my `OriginateAction` I am able to sent it `Async = true` which means that I don't get a responce about rather or not it was successful, but there does not seem to be the same option available for `RedirectAction`.
Here is my `OriginateAction` for comparison:
``` csharp
ManagerResponse originateResponse = myManagerConn.SendAction(new OriginateAction()
{
    Channel = "SIP/" + sip,
    Exten = exten,
    Context = _context,
    Priority = "1",
    CallerId = callerId + " <" + sip + ">",
    Timeout = 120000, // 2 minutes.
    Async = true
});
```

I also noticed that `Priority` is an `int` in `RedirectAction`, but a `string` in `OriginateAction`.

**Comment by Deantwo** [comment]
I guess I can call it asynchronously using `SendAction(ManagerAction action, ResponseHandler responseHandler)` and just leave the second argument `null`.
According to a comment in that method, that would result in just no response at all.
See: [ManagerConnection.cs#L1960](https://github.com/AsterNET/AsterNET/blob/61ff9425eab379d31b8213ef76fe7ace51243426/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1960)

**Comment by skrusty** [comment]
Hi,
Just a quick look at the RedirectAction on Asterisk AMI docs, it doesn't have an Async flag.

https://wiki.asterisk.org/wiki/display/AST/ManagerAction_Redirect

To be honest, it's not something i've used in a long time.

Can you provide some more information about the timeout? Is it happening right away, or after you send the request but timeout happens while waiting for the redirect to complete?

Cheers,
Ben

**Comment by Deantwo** [comment]
Ok, I seem to have found my issue with the timeout exception.

Seems to just happen if I try to redirect the same channel twice. Which I guess makes sense. Now I just have to make it not able to do that somehow without crashing my stupid DataGridView.

But yeah, I found out after posting that there was no mention of `Async` in Asterisk's documentation. I am just surprised at how different these actions are.
