### ISSUE TITLE
AsterNet Login Authentication Fail [need help]

### ISSUE THREAD

**Issue by cjimloo** [AsterNET/AsterNET#88]
I am new to AsterNET. Hope can get some help here:

The Program through an error message "Authentication Fail" when I was trying to login with the sample code (Folder Asterisk 2013)  even though the user name and password is correct.

What else do I need to config? 

Here is my code:

`Imports AsterNET
Imports AsterNET.Manager
Imports AsterNET.Manager.Event
Imports AsterNET.FastAGI.Command
Imports AsterNET.FastAGI
Imports AsterNET.IO
Imports System.Text
Imports System.Data.Sql

Public Class Form1
    Dim host As String = "172.31.31.201"
    Dim port As Short = 5038
    Dim user As String = "222"
    Dim pass As String = "222"
    Dim conn As New ManagerConnection(host, port, user, pass)
    Dim exten As Short = 201
    Dim state As String = "state"

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Try

            conn.Login()

        Catch ex As Exception
            MsgBox("Error logging on")

        End Try
        If conn.IsConnected Then
            MsgBox("Yo!! Connected!")
        End If

    End Sub
End Class
`

**Comment by skrusty** [comment]
Is ami enabled in Asterisk?

**Comment by zidanekhanStudent** [comment]
You have to  write in manager_custom.conf or  manager_additional.conf files.These are the files present inside asterisk server

// You have to write like this in any one of this file
[abc]
secret = 123
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.0
permit = 192.168.211.129/255.255.255.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate

Then you have to write in your code to connect to asterisk or AMI
Code section

  const string DEV_HOST = " 192.168.211.129";
        const int ASTERISK_PORT = 5038;
        const string ASTERISK_HOST = "192.168.211.129";
        const string ASTERISK_LOGINNAME = "abc";
        const string ASTERISK_LOGINPWD = "123";

**Comment by manika880** [comment]
I am also facing the same problem. In fact i wrote the above piece of code in manager_additional.conf/manager_custom.conf file but still problem is staying in the code.
What should i need to check again in my code or asterisk ?

**Comment by rex644** [comment]
I am having the same issue:
https://github.com/AsterNET/AsterNET/issues/112

**Comment by rex644** [comment]
I figured it out: https://github.com/AsterNET/AsterNET/issues/112
