### ISSUE TITLE
Filter Action

### ISSUE THREAD

**Issue by zsender** [AsterNET/AsterNET#90]
I want to ask, why not create a FilterAction? I

class FilterAction : ManagerAction
 {
        /// <summary>
        /// Add - Add a filter
        /// </summary>
        public string Operation { get; set; }

        /// <summary>
        /// Filters can be whitelist or blacklist
        /// Example whitelist filter: "Event: Newchannel"
        /// Example blacklist filter: "!Channel: DAHDI.*"
        /// </summary>
        public string Filter { get; set; }
    }

**Comment by skrusty** [comment]
Sorry, not sure I understand the question.

**Comment by zsender** [comment]
I mean, the asterisk API have command action "Filter" and "FilterList". This command make it possible add action event to white or black lists. This features is useful when we have many calls and asterisk send a lot of packets.  You don't implemented this action in your library. This is due to the versions of asterisk or it will be implemented at next versions?

**Comment by skrusty** [comment]
Simply not been added, if you'd like to add it, we'd welcome your pull request!

Cheers
