### ISSUE TITLE
QueueEntryEvenet Missing CallerIDNum

### ISSUE THREAD

**Issue by Deantwo** [AsterNET/AsterNET#91]
[QueueEntryEvent.cs](https://github.com/AsterNET/AsterNET/blob/3c34e430d0029c99caf237e2769de7f0f512c568/Asterisk.2013/Asterisk.NET/Manager/Event/QueueEntryEvent.cs) does not have a property for `CallerIDNum`. It is instead added in under [`Attributes`](https://github.com/AsterNET/AsterNET/blob/3c34e430d0029c99caf237e2769de7f0f512c568/Asterisk.2013/Asterisk.NET/Manager/Event/ManagerEvent.cs#L45).

Same with `ConnectedLineNum` and `ConnectedLineName`, but I have no relationship to those.

I can't find any of the queue status events on the [asterisk wiki](https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+AMI+Events). Only ever found it on [voip-info.org](https://www.voip-info.org/wiki/view/Asterisk+Manager+API+Action+QueueStatus).

Using a PHP script to query for the QueueStatus as a test I get the following:
```
Event: QueueEntry
Queue: 100
Position: 1
Channel: SIP/SIPTRUNKGC-00000000
Uniqueid: 0000000000.000000
CallerIDNum: 12345678
CallerIDName: Deantwo
ConnectedLineNum: unknown
ConnectedLineName: unknown
Wait: 42
```

**Asterisk version:** 1.8.21

**Comment by Deantwo** [comment]
I haven't found where in the code that events are created, so I don't know how to fix it myself yet. If I find out how to fix it, I will create a pull request.

**Comment by skrusty** [comment]
1.8 is older than 14.

**Comment by Deantwo** [comment]
Than I guess I am wrong here, so sorry for disturbing you.
I should bug my technical department to upgrade maybe.
