### ISSUE TITLE
ControlPlayback

### ISSUE THREAD

**Issue by VsevolodGavrilov** [AsterNET/AsterNET#95]
Does Aster,Net some how supports ControlPlayback action? I don't see the corresponding class in the project. 
https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+ManagerAction_ControlPlayback 

My task is to play mp3 file in a conference room (play, rewind, pause, stop). Maybe I can solve the task through any kind of other functionallity in Aster.Net?
Thanks!

**Comment by skrusty** [comment]
It's quite possible this has snot yet been implemented in AsterNET AMI.

Two options, 

1 Implement it and we would love a PR from you with it in.
2 Look at using ARI. Could give you a lot more control, but may be more work, depending on the scope of your project.

Cheers
