### ISSUE TITLE
GeneralMappingStrategy using XML

### ISSUE THREAD

**Issue by DaveTTS** [AsterNET/AsterNET#98]
HI all

Really useful library!  Saving me a lot of time, however I have an issue I currently don't know how to fix.  I am trying to use XML for my GeneralMappingStrategy in Asternet. I have my program working fine using List such as:

`agiServer.MappingStrategy = new GeneralMappingStrategy(
        new List<ScriptMapping>()
        {
            new ScriptMapping() {
            ScriptName = "testIVR",
            ScriptClass = "Asterisk_Test.testIVR",
            }
        });`

But I'd rather have it read an XML file as it says it can do in the documentation, however it does not seem to say anywhere what the XML format is required.
I have tried:

`string pathtoxml = "test.xml";
agiServer.MappingStrategy = new GeneralMappingStrategy(pathtoxml);`

With my XML as:

`<?xml version="1.0"?>
<ScriptMapping>
<ScriptName>testIVR</ScriptName>
<ScriptClass>Asterisk_Test.testIVR</ScriptClass>
</ScriptMapping>`

As a complete guess, seemed to make sense, but this won't compile, I get errors of:

System.InvalidOperationException: 'There was an error reflecting type 'System.Collections.Generic.List`1[AsterNET.FastAGI.MappingStrategies.ScriptMapping]'.'

If possible can you let me know what I am doing wrong please?

Cheers

David

**Comment by skrusty** [comment]
I don't have an example to hand, however you might want to try generating the mappings using the ScriptMapping.SaveMappings()'s method. THis should then give you the correct XML.

Cheers,
Ben

**Comment by DaveTTS** [comment]
Hi Ben

Thanks so much for the reply, I appreciate your time.  I have just tried that, and I get the same error, here's my code:

List<ScriptMapping> IVR_RunKeys = new List<ScriptMapping>();

AsteriskFastAGI agiServer = new AsteriskFastAGI();
string pathtoxml = "C:\\temp\\test.xml";
List<ScriptMapping> IVR_RunKeys = new List<ScriptMapping>();
            IVR_RunKeys.Add(new ScriptMapping()
            {
                ScriptName = "testIVR",
                ScriptClass = "Asterisk_Test.testIVR",
            });
            IVR_RunKeys.Add(new ScriptMapping()
            {
                ScriptName = "testIVR2",
                ScriptClass = "Asterisk_Test.testIVR2",
            });

ScriptMapping.SaveMappings(pathtoxml, IVR_RunKeys);

It fails to compile with the following errors:

System.InvalidOperationException: 'There was an error reflecting type 'System.Collections.Generic.List`1[AsterNET.FastAGI.MappingStrategies.ScriptMapping]'.'

InvalidOperationException: There was an error reflecting type 'AsterNET.FastAGI.MappingStrategies.ScriptMapping'.

InvalidOperationException: There was an error reflecting property 'PreLoadedAssembly'.

InvalidOperationException: There was an error reflecting type 'System.Reflection.Assembly'.

InvalidOperationException: You must implement a default accessor on System.Security.Policy.Evidence because it inherits from ICollection.

Many thanks if you could have a further look into this.

David

**Comment by skrusty** [comment]
Looks like we're missing an XmlIgnore attribute on the PreLoadedAssembly property.

Can you pull from source and try adding that attribute, then testing again? If that works, please feel free to submit a Pull Request.

Thanks
Ben

**Comment by DaveTTS** [comment]
Hi Ben

I have pulled from source and added it in:

[XmlIgnoreAttribute]
public Assembly PreLoadedAssembly { get; set; }

You are right this then fixes it and it all works.  XML is produced with the ScriptMapping.SaveMappings()'s method.

I don't appear to be able to do a pull request for the change?

One other thing I also noticed in the master when I was testing, which is a bit odd to me, is that it was crashing with a null object, this was in AsteriskFastAGI.cs in Start()

it has:

            finally
            {
                if (serverSocket != null)
                {
                    serverSocket.Close();
                    serverSocket = null;
                }

                pool.Shutdown();
#if LOGGER
                logger.Info("AGIServer shut down.");
#endif
            }

Which is causing the null error, I don't understand why the server socket would be closed down when it has only just been opened and thus it causes an error with:

 while ((socket = serverSocket.Accept()) != null)

Thanks

David

**Comment by DaveTTS** [comment]
Worked out the pull request!!! First time contributor to GitHub - Sorry!

**Comment by skrusty** [comment]
Fixed by #99
